### ISSUE TITLE
Selection Tool ?

### ISSUE THREAD

**Issue by Maverick83000** [3liz/lizmap-web-client#1675] opened 2020-06-09 09:38 UTC
Hi,
How can I get, like in the demo project "Paris by Night", the geographic selection tool, represented by a star's icon in the bar menu ? 

Thanks for your help

**Comment by nboisteault** [comment] 2020-06-09 10:07
You need to add layers in Lizmap plugin in attribute table tab => https://docs.lizmap.com/current/en/publish/advanced_lizmap_config.html#show-attribute-table-for-lizmap-layers

**Comment by Gustry** [comment] 2020-06-09 10:07
You need to enable the attribute table tool on that layer.
If you don't want the attribute table, you can then hide it.

**Comment by Maverick83000** [comment] 2020-06-09 11:57
Thanks! It works.
Sorry for this obvious question.

I'have another question : I want to have the projects's informations in a popup when I load a project (like the projects in the demo) 
Should I open another issue for this?

Thank you

**Comment by Gustry** [comment] 2020-06-09 12:11
> I'have another question : I want to have the projects's informations in a popup when I load a project (like the projects in the demo)

https://github.com/3liz/lizmap-javascript-scripts/

Look for `popup`, you will find it. And also the link to the documentation how to add javascript.

I'm closing as the issue is solved. Thanks for your inputs.

**Closed by Gustry** 2020-06-09 12:11 UTC
Labels: question
