### ISSUE TITLE
Filter by user doesn't work anymore

### ISSUE THREAD

**Issue by mfangain** [3liz/lizmap-web-client#825] opened 2018-03-28 15:22 UTC
Hi,
In one project, I used the fonction "filter by user", to restrict the access to the data.
I observe today that it doesn't work anymore. I don't see any error message, but all users can see all data in spite of settings.

Thanks.

MFANGAIN

**Comment by rldhont** [comment] 2018-04-07 14:42
Does the filter concerned a layer with a space in the name ?

**Comment by mfangain** [comment] 2018-04-09 13:32
Hi,
Yes, there's a space in the name.
When I replace it by '_' for example, it works properly.

Thank you.

MFANGAIN

**Comment by nboisteault** [comment] 2018-09-14 15:34
I can't reproduce the issue with a layer with a space in its name.
I've used Lizmap 3.1.14, QGIS Server 2.18.23 and my layer is a Postgis one. 
@mfangain do you still have this issue ?

**Comment by mfangain** [comment] 2018-09-17 11:54
Hello,

Yes, the issue still occurs, with Lizmap 3.1.14.
There's no space on table name in Postgis, but the issue appear when there is a space on the layer name in QGIS project.

Thanks :D 

MFANGAIN

**Comment by nboisteault** [comment] 2018-09-19 13:54
Which QGIS Server version do you use ?

**Comment by mfangain** [comment] 2018-09-19 14:44
Hi,

I don't know, Lizmap is hosted by 3Liz.

But Lizmap 3.2 has been installed yesterday.
This issue seems in part resolved in this version : 
- on the map, filter is well done even there's a space on the layer name
- but not on the attribute table panel : user sees all data (note that filter is well done when there's no space in layer name)

**Comment by rldhont** [comment] 2018-10-18 09:01
It has been fixed by e22d9f470fea94a56072432535bcae904d61baf8

**Closed by rldhont** 2018-10-18 09:01 UTC
Labels: bug, feedback
