### ISSUE TITLE
[Bug]: 3.8 RC 2: Layer group not automatically active despite corresponding setting (group as Layer)

### ISSUE THREAD

**Issue by guenterw** [3liz/lizmap-web-client#4593] opened 2024-07-09 16:44 UTC
### What is the bug? (in English)

Layergroups that are grouped in a layer (group as layer) are not automatically displayed as active, even if this is defined as such.
This is known for version 3.7.9 (#4382) and is also in the milestones for 3.7.10. 
However, it also does not work in 3.8 RC 2
![image](https://github.com/3liz/lizmap-web-client/assets/8373176/8025a03a-c4d5-4ce1-8e98-b85061ded823)

![image](https://github.com/3liz/lizmap-web-client/assets/8373176/fb8625bb-002c-4272-b707-e1612595e3cb)
https://cx21-8.webgis.biz/index.php/view/map?repository=alkis&project=Test_Herbolzheim8

It does not matter whether QGIS themes are used or not. It does not work with both.

If the layergroup is not grouped, it works.
But then in this example I have 57 layers in the group instead of 1 grouped layer group.

### Steps to reproduce the issue

See What is the bug

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.8.0-rc.2
* Lizmap plugin : 4.3.19
* QGIS Desktop : 3.34.8
* QGIS Server : 3.34.8
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.4.1
* QGIS Server plugin cadastre : 1.19.2
* QGIS Server plugin lizmap_server : 2.9.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : yes
* Number of parent : 2 folder(s)
* Prevent other drive : no
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04 (Server)

### Browsers

Chrome

### Browsers version

Chrome Version 126.0.6478.127

**Comment by Gustry** [comment] 2024-07-15 09:43
Hi @guenterw I'm closing here, as you have mentioned yourself, there is already #4382 please add more info there if necessary.

Duplicate of #4382

**Closed by Gustry** 2024-07-15 09:43 UTC
Labels: bug

**Comment by guenterw** [comment] 2024-07-15 09:54
ok, with the request to include this in the milestones of 3.8.

Taking this error into account is very time-consuming for me. In order to use an extensive grouped layergroup, I now provide this myself as a WMS service. I have to change the many "small" grouped layergroups accordingly.
And I don't know whether the work is worth it or whether I should wait for the bug to be fixed. 
Would a financial contribution towards fixing the error help?

**Comment by Gustry** [comment] 2024-07-15 09:59
Do not take care of milestones ;-)
Please comment on the opened ticket, thanks.
