### ISSUE TITLE
attribute table - media and url links

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#1167] opened 2019-04-04 08:11 UTC
hi

if the layer name `Quartiers XXX` contains a blank spaces the path or url is displayed instead of the field alias

![imagem](https://user-images.githubusercontent.com/10053874/55539478-a1cc4200-56b8-11e9-8830-82d6d4d7870c.png)

lwc 3.2 and master
qgis server 2.18 and 3.4

thanks

**Comment by nboisteault** [comment] 2019-04-04 09:08
@rldhont This issue is independant from #1156. The problem is space in typename for DescribeFeatureType request.

**Comment by nboisteault** [comment] 2019-04-04 12:37
@rldhont is DescribeFeatureType supposed to accept typename with space in it ?

**Comment by rldhont** [comment] 2019-04-04 12:41
In WFS, we have to use the typename provided by the getcapabilities

**Comment by nboisteault** [comment] 2019-04-04 13:15
@rldhont :
`<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:gml="http://www.opengis.net/gml" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:qgs="http://www.qgis.org/gml" targetNamespace="http://www.qgis.org/gml" elementFormDefault="qualified" xmlns:ogc="http://www.opengis.net/ogc" version="1.0">
 <import namespace="http://www.opengis.net/gml" schemaLocation="http://schemas.opengis.net/gml/2.1.2/feature.xsd"/>
 <element name="Quartiers_XXX" type="qgs:Quartiers_XXXType" substitutionGroup="gml:_Feature"/>
 <complexType name="Quartiers_XXXType">
  <complexContent>
   <extension base="gml:AbstractFeatureType">
    <sequence>
     <element name="geometry" maxOccurs="1" type="gml:MultiPolygonPropertyType" minOccurs="0"/>
     <element name="QUARTIER" type="int" nillable="true"/>
     <element name="QUARTMNO" type="string" nillable="true"/>
     <element name="LIBQUART" alias="Name" type="string" nillable="true"/>
     <element name="SQUARTMNO" type="string" nillable="true"/>
     <element name="photo" alias="Illustration" type="string" nillable="true"/>
     <element name="url" alias="Website" type="string" nillable="true"/>
    </sequence>
   </extension>
  </complexContent>
 </complexType>
</schema>
`

**Comment by rldhont** [comment] 2019-04-04 17:23
PR has been merged

**Comment by josemvm** [comment] 2019-04-04 18:23
@rldhont and @nboisteault thanks :-)

**Closed** 2019-04-05 14:40 UTC
Labels: bug
