### ISSUE TITLE
Google Analytics alternative -> Matomo

### ISSUE THREAD

**Issue by igeofr** [3liz/lizmap-web-client#1726] opened 2020-07-18 13:45 UTC
### Is your feature request related to a problem? Please describe
Add a way to track site analytics with [Matomo](https://matomo.org).

**Comment by Gustry** [comment] 2022-09-21 13:25
Duplicate of #2836 

Your ticket was opened before, but there were more discussions on the other one, so I'm closing this one.

**Closed by Gustry** 2022-09-21 13:25 UTC
Labels: enhancement
