### ISSUE TITLE
[Bug]: WMS legend not shown any longer in LWC 3.7+ for non-baselayer WMS layer

### ISSUE THREAD

**Issue by maxencelaurent** [3liz/lizmap-web-client#4317] opened 2024-03-21 08:56 UTC
### What is the bug? (in English)

In previous version of LWC, legends of WMS layers legend were displayed in the layer switcher. This is no longer the case in LWC 3.7.

Up to 3.6, the legend of all the layer types was requested from the server with a `GetLegendGraphic`  query.
Since 3.7, legend of vector layer is built client-side (which is way nicer !!!). It seems the support for WMS-layers legend has been droped in the process.

Not having the legend for thematic WMS layers is a major issue.

# Example 
## Layer Source
- URL:  https://www.ogc.vd.ch/public/services/OGC/wmsVD/Mapserver/WMSServer
- name:  vd.glissement_DUTI
- source: crs=CRS:84&dpiMode=7&format=image/png&layers=vd.glissement_DUTI&styles&url=https://www.ogc.vd.ch/public/services/OGC/wmsVD/Mapserver/WMSServer
- provider: WMS

## Legend in QGIS
![Legend_in_qgis](https://github.com/3liz/lizmap-web-client/assets/6583528/79c13129-3eb0-4690-9b5d-70664d68cddb)

## Legend in LWC 3.6.10
![Legend_In_LWC_3 6 10](https://github.com/3liz/lizmap-web-client/assets/6583528/26805a10-5da4-4650-8bf4-dd2f2afc27d5)

## Legend in LWC 3.7.5
No way to display the legend, the caret is not even there.
![Layers_in_LWC_3 7 5](https://github.com/3liz/lizmap-web-client/assets/6583528/dd45932c-6f68-40ca-b454-b9b63e1f5246)

### Steps to reproduce the issue

1. Add a WMS layer in your QGIS project
2. View the project in LWC 3.7+

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.5
* Lizmap plugin : 4.2.7
* QGIS Desktop : 3.28.15
* QGIS Server : 3.28.13
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.6
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 23.10

### Browsers

Firefox, Chrome

### Browsers version

Firefox 124; Chromium 122

### Relevant log output

```shell
no relevant data
```

**Comment by Gustry** [comment] 2024-03-21 09:17
It's a duplicate of #4036, please report your example there, thanks.

**Closed by Gustry** 2024-03-21 09:17 UTC
Labels: bug

**Comment by maxencelaurent** [comment] 2024-04-02 12:56
Actually it's more a duplicate of  #1571 ;-)
