### ISSUE TITLE
"Locate by layer" works if layer is GPKG but not if is PostGIS

### ISSUE THREAD

**Issue by gioman** [3liz/lizmap-web-client#2309] opened 2021-05-26 23:25 UTC
LMWC 3.4.3 and QGIS Server 3.16 on Ubuntu Server 20.04

I have layer (which I cannot share here, but could do it privately) that when added to a project will works fine when used in the "Locate by layer" functionality as a GPKG datasource but it does not when imported into a PostGIS db. I tried to troubleshoot the problem with no success. Seems a bug to me but I can be wrong of course.

**Comment by Gustry** [comment] 2021-05-27 00:06
Is-it a PostgreSQL service file ?

**Comment by gioman** [comment] 2021-05-27 07:53
@Gustry thanks for the feedback



> Is-it a PostgreSQL service file ?

no, the project uses plain text credentials



>  Is the layer in PG working fine ?

yes. 

>  Maybe you can share just the XML of the datasource in the QGS project ? (the string with `host=...`)

<datasource>dbname='***' host=*** port=5432 user='***' password='***' sslmode=disable key='id' srid=3763 type=Polygon checkPrimaryKeyUnicity='1' table="testes"."lea" (geom)</datasource>



> Any error in the webbrowser console ?

no errors in FF web console.


I just found that if I remove some columns from this postgis layer then it works as expected. The columns I removed were of type int8, the postgis layer was imported from a gpkg (using QGIS) where this columns were given the integer64 type (not sure why, it wasn't me that created this gpkg)

Do you want me to send you the layer?

**Comment by Gustry** [comment] 2021-05-27 08:40
It's a known issue with PostGIS on QGIS server and int4 int8 fields. I think there have been some progress on QGIS Server recently @rldhont ?

**Comment by Gustry** [comment] 2021-05-27 08:41
Duplicate of https://github.com/3liz/lizmap-web-client/issues/1745 ?

**Comment by gioman** [comment] 2021-05-27 09:45
> Duplicate of #1745 ?

 @Gustry this seems about using int8 for the PK, which is not my case. Anyway my finding may be misleading, in fact I just found a similar layer/table (identical in structure as the other in fact) that works fine together with "locate by layer"...

**Comment by nboisteault** [comment] 2021-09-13 16:09
Please reopen if issue still occurs.

**Closed by nboisteault** 2021-09-13 16:09 UTC
Labels: bug, QGIS Server
