### ISSUE TITLE
Seeding Script Error

### ISSUE THREAD

**Issue by zoidable** [3liz/lizmap-web-client#720] opened 2017-11-30 10:39 UTC
Hi,

when I try to run the seeding script (lizmap/scripts/script.php), I get the following error message: 

```
Error during initialization: \n* Error in main configuration on pluginsPath -- P
ath given in pluginsPath for the module jacl2db is ignored, since this module is
 unknown or deactivated (C:\Webserver\lizmap\prod\master\lib\jelix\core\jConfigC
ompiler.class.php 423)
* Error in the main configuration. A plugin doesn't exist -- The coord plugin ja
cl2 is unknown. (C:\Webserver\lizmap\prod\master\lib\jelix\core\jConfigCompiler.
class.php 164)
```

Any hints would be appreaciated :)

Thanks

**Comment by josemvm** [comment] 2017-11-30 10:42
https://github.com/3liz/lizmap-web-client/issues/689

**Comment by zoidable** [comment] 2017-12-01 09:23
Using PHP 7.1 and tested with master and 3.1 release btw.

**Comment by josemvm** [comment] 2017-12-01 09:34
hi @zoidable 

what php version are you using before?

**Comment by zoidable** [comment] 2017-12-01 09:52
hi @josemvm 
i just had a fresh start with php 7.1 since i'm new to webgis/web map applications (kinda glad already that everything except the seeding script seems to run smoothly).

**Comment by zoidable** [comment] 2017-12-02 09:59
also tested with php 5.6 and 7.2 now with the same result/no success. at one time, the error message was the same as in #689 but i wasn't able to reproduce it.

**Comment by zoidable** [comment] 2017-12-04 18:39
while i was looking for a workaround to pregenerate the cache i realized that the naming and folder structure from lizmap generated tiles is very different from tms or slippy map conventions, and the filetype is .CACHE instead of png or jpeg - is this working as intended? 

is there a way to use tools (e.g. QTiles) other than the seeding script to pregenerate tiles for the lizmap cache folder?

**Comment by rldhont** [comment] 2017-12-05 17:15
It seems to be an error in the lizmap installation. The script config does not have all the needed modules. Can you replay:
```
sudo lizmap/install/set_rights.sh www-data www-data
sudo lizmap/install/clean_vartmp.sh
php lizmap/install/installer.php
sudo lizmap/install/clean_vartmp.sh
```

**Comment by zoidable** [comment] 2017-12-05 19:01
hi @rldhont, thanks for the reply! i'm running windows, but i just deleted the content of the folders mentioned in clean_vartmp.sh, ran the installer again and it worked! 
however, i think i'm experiencing another error (or probably misconfiguration on my side) now, since the script returns that several million tiles have to be created for EPSG:3857 and zoom level 14 and 15 in the demo project...that seems a bit much :)

**Comment by laurentj** [comment] 2017-12-12 15:59
Does this error appear after a fresh installation ? after a change in the web server configuration ? after an upgrade of Lizmap ? after an upgrade of PHP ? Did this script worked correctly in the past and if yes, what changes did you made in lizmap, in the web server etc. ?

**Comment by laurentj** [comment] 2017-12-14 22:03
I cannot reproduce the error, and it seems it is solved. I close the issue. Reopen it if you encounter again this error about the jacl2db plugin

**Closed by laurentj** 2017-12-14 22:03 UTC
Labels: bug, jelix
