### ISSUE TITLE
[Bug]: Bootstrap 5: popup tabs not working anymore

### ISSUE THREAD

**Issue by mind84** [3liz/lizmap-web-client#4748] opened 2024-09-13 11:14 UTC
### What is the bug? (in English)

After moving to Bootstrap 5 (see #4455), if you use QGIS Drag and Drop design for tooltips, and you set some `tabs` in the layout, then on client these tabs are not working anymore (e.g. when you click on tabs then the corresponding content is not showed)

![image](https://github.com/user-attachments/assets/4607f99a-5f16-41f5-b424-887c20d778a1)

@Gustry  I think this could be fixed on the `lizmap-server-plugin` by add proper classes to `html` elements, for example on this line:

https://github.com/3liz/qgis-lizmap-server-plugin/blob/b17cd00abbdf7b2274c2aea3fafb2c817588553a/lizmap_server/tooltip.py#L177

Thanks

### Steps to reproduce the issue

Described above.

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.9.0-pre
* Lizmap plugin : 4.3.20
* QGIS Desktop : 3.34.3
* QGIS Server : 3.34.8
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.10.1
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : normal
* Allow parent folder : yes
* Number of parent : 7 folder(s)
* Prevent other drive : no
* Prevent PG service : no
* Prevent PG Auth DB : no
* Force PG user&pass : no
* Prevent ECW : no
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Debian

### Browsers

Firefox, Chrome

### Browsers version

latest

**Comment by Gustry** [comment] 2024-09-13 12:12
Sorry, I'm closing as duplicate of https://github.com/3liz/lizmap-plugin/issues/592

@nboisteault @mind84 I will need some help of you.

**Closed by Gustry** 2024-09-13 12:12 UTC
Labels: bug

**Comment by mind84** [comment] 2024-09-13 12:16
Uops, sorry, didn't notice that.

I'm making a PR
