### ISSUE TITLE
[Bug]:  display of layer labels

### ISSUE THREAD

**Issue by JBL034** [3liz/lizmap-web-client#3317] opened 2022-11-07 14:46 UTC
### What is the bug?

the display of layer labels does not work in 3.5 with QGis desktop 3.10 or 3.28. (it works in desktop 2.18 !!!) .
Do you know this problem? you can help me ?

### Steps to reproduce the issue

project generated with QGis 2.18 (labels are ok) : https://ewatch-carto.pro/lizmap/index.php/view/map/?repository=cartomada&project=DINAMAP-JBL-2_18

project generated with QGis 2.18 (labels are ok) : https://ewatch-carto.pro/lizmap/index.php/view/map/?repository=cartomada&project=DINAMAP-JBL-3-10
 

### Versions

version 3.5.7

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

ubuntu

### Browsers

Firefox, Chrome

### Browsers version

Firefox 106

**Comment by Gustry** [comment] 2022-11-07 15:05
In your QGIS desktop 3.10 or 3.28, you must follow the issue template about the Lizmap plugin
https://docs.lizmap.com/current/fr/publish/lizmap_plugin/information.html#request-for-support

**Comment by Gustry** [comment] 2022-11-07 15:12
Duplicate of https://github.com/3liz/lizmap-web-client/issues/1513 and https://github.com/3liz/lizmap-web-client/issues/1660 ?

I think you are using QGIS Server 2.18 ?
QGIS Server 2.18 can't read a project in the future (with QGIS 3.X).

Please reopen if you are using QGIS 3.22 (same version as desktop)

**Closed by Gustry** 2022-11-07 15:12 UTC
Labels: bug, feedback
