### ISSUE TITLE
Problem configuring PostgreSQL as a database for Lizmap

### ISSUE THREAD

**Issue by franyam2006** [3liz/lizmap-web-client#1837] opened 2020-09-23 16:48 UTC
### Environment

 - Lizmap version: 3.3.6
 - QGIS Server FULL version: 3.10.1
 - QGIS Desktop FULL version: 3.10
- PostreSQL version : 11
 - OS (Windows, Linux, MacOS, Android…): Windows 10
 - Browser (Firefox, Chrome…): Chrome
 - Lizmap admin information (users, logs…) stored into Sqlite (default)? PostgreSQL? MySQL?  Sqlite, PostgreSQL

Good morning all  !

I am a new user of Lizmap. I installed it on my PC and it works fine. I want to use PostgreSQL as a database, so according to the instructions in the lizmap documentation, I set my file .... \ lizmap-web-client-3.3.6 \ lizmap \ var \ config \ profiles.ini.php as follows :

[jdb]

; name of the default profile to use for any connection
default=jauth
jacl2_profile=jauth

;[jdb:jauth]
;driver=sqlite3
;database="var:db/jauth.db"

;[jdb:lizlog]
;driver=sqlite3
;database="var:db/logs.db"

**[jdb:jauth]
driver=pgsql
database=lizmap_base
host=localhost
user=postgres
password=12345

[jdb:lizlog]
driver=pgsql
database=lizmap_base
host=localhost
user=postgres
password=12345**

---------------------------------------------------------------------------

After that I reinstall the lizmap web client from the command line:

cd C:\xampp\lizmap\prod\lizmap-web-client-3.3.6\
cd lizmap\var\config
copy lizmapConfig.ini.php.dist lizmapConfig.ini.php
copy localconfig.ini.php.dist localconfig.ini.php
copy profiles.ini.php.dist profiles.ini.php
cd ..\..\..

cd C:\xampp\lizmap\prod\lizmap-web-client-3.3.6\
php lizmap\install\installer.php

I  specify that the password here (12345)
this is the password to access my database (lizmap_base) in PostgreSQL and not the password to access PostgreSQL itself. see image below
![liz](https://user-images.githubusercontent.com/61616432/94041270-8a57ac00-fdb9-11ea-911a-90dad39adf0b.PNG)

Then I load my layers in QGIS through PostGIS and I configure the QGIS project and with the lizmap plugin and I save in the production folder. At the end when I run lizmap http: //localhost/webgis/index.php it displays SERVICE UNAVAILABLE. What went wrong? Can someone pinpoint where exactly the fault is? If someone has already done this using PostreSQL and it works perfectly, please help me! 

Thank you very much to the whole community. I hope my explanations are a little clear. If there are any questions I am here to answer you to make my concern even more understandable.

**Comment by Gustry** [comment] 2020-09-24 07:33
Closing as duplicate of #1836

**Closed by Gustry** 2020-09-24 07:33 UTC
Labels: question
