### ISSUE TITLE
Mobile - Print settings window

### ISSUE THREAD

**Issue by igeofr** [3liz/lizmap-web-client#1157] opened 2019-04-01 16:30 UTC
### What is the bug?
On my phone, it is impossible to access all print settings.

### Screenshots and logs
![IMG_7061](https://user-images.githubusercontent.com/7761073/55343742-3f4a2a80-549b-11e9-99a2-81c55032443a.PNG)

### Environment

- Lizmap version: 3.2.2
- QGIS Server version: 2.18
- QGIS Project version: 2.18.28
- OS (windows, linux, macOS, android..): iOS 10.3.3
- Browser (Firefox, Chrome...): Safari

**Comment by nboisteault** [comment] 2019-04-08 13:22
Duplicate of #1151

**Closed by nboisteault** 2019-04-08 13:22 UTC
Labels: bug, mobile, user interface
