### ISSUE TITLE
Enhancement: possibility to insert in lizmap plugin the Title of the project, title of each layer and the aliases of the fields in different languages

### ISSUE THREAD

**Issue by jaitor1** [3liz/lizmap-web-client#180] opened 2015-07-10 11:10 UTC
Hi,

Lizmap's language is automatically set getting the language from the browser's config. 

It can be changed by hand adding "&lang=en_US" parameter.

The thing is that only the text related to lizmap's interface is translated. The Title of the project, the title of each layer and the fields' aliases are still dispalyed in the language that were inserted in QGIS (only one).

I think it would be a great feature (for example for turism related maps in my case) to be able to insert the translation for all these features (project title, layers' titles and layer fields' aliases) in the locales available in lizmap so that the map would be fully displayed in that language, not only the interface.

**Comment by rldhont** [comment] 2016-04-22 15:56
Now, QGIS Server has INSPIRE information (version 2.14), it will be a nice feature.

**Comment by nboisteault** [comment] 2022-01-10 19:36
Duplicate of #453

**Closed by nboisteault** 2022-01-10 19:36 UTC
Labels: enhancement
