### ISSUE TITLE
Demo (Montpellier) doesn't appear in LWC 3.4.x installation

### ISSUE THREAD

**Issue by dobignies** [3liz/lizmap-web-client#2234] opened 2021-04-09 13:07 UTC
### What is the bug?
Hi,
I update Qgis and LWC, but there is something wrong in the check demo (Montpellier) step, it doesn't appear. I can connect, change pw, access config menu, but there is no create repository option/button. I have tested LWC 340rc1, 340rc2, 341, 342 too. The 3.3.15 is ok. Is that a permission setup issue?

WINDOWS 10 (64-bit)
Firefox 87.0 (64-bit)
QGIS 3.18.1
httpd-2.4.46-win64-VS16
php-7.3.27-nts-Win32-VC15-x64
lizmap-web-client-3.4.3
mod_fcgid-2.3.10-win64-VS16
VC_redist.x64

**Comment by gioman** [comment] 2021-04-09 13:16
@dobignies duplicate of https://github.com/3liz/lizmap-web-client/issues/2222

**Comment by dobignies** [comment] 2021-04-09 13:23
@gioman #2222 is Ubuntu server issue

**Comment by Gustry** [comment] 2023-07-18 17:20
Is this issue still valid ?

We have demo working on our machine when launching the docker test stack.

**Comment by gioman** [comment] 2023-07-19 07:43
> We have demo working on our machine when launching the docker test stack.

@Gustry the last time I tried (and was not long ago) the demo dataset was not anymore part of the code cloned via git, so adding the "demo" config during set up as no effect when installing directly on the OS (not docker).

**Comment by Gustry** [comment] 2023-07-19 08:26
> the last time I tried (and was not long ago) the demo dataset was not anymore part of the code cloned via git

It's here : https://github.com/3liz/lizmap-web-client/tree/master/extra-modules/lizmapdemo/qgis-projects
But except if you are a developer, we do not recommend using git, as you must build the application. We recommend using the ZIP.

When packaging, it's now a separate module, not shipped in the default zip : https://packages.3liz.org/pub/lizmap/release/3.6/ at the bottom

Did you see https://github.com/3liz/lizmap-web-client/blob/master/INSTALL.md#test ?
I made a PR, waiting for review from my colleague.

**Comment by Gustry** [comment] 2023-07-19 11:28
Assets are added automatically by our CI process. I can think about it. But I don't this needed ?

The script provided is already taking care of it : https://github.com/3liz/lizmap-web-client/blob/master/lizmap/install/demo.sh#L37

**Closed** 2023-07-20 09:51 UTC
Labels: bug, feedback
