### ISSUE TITLE
Print issue with "integrated layers and groups".

### ISSUE THREAD

**Issue by geoek** [3liz/lizmap-web-client#236] opened 2015-12-29 14:32 UTC
Hi,
I have a problem to print (lizmap 2.12 and beta 3)

I built a basemap layer from several vector layers. I use this basemap in a project and I can print normally.

In another project, I loaded this basemap with the tools "integrated layers and groups". This works fine for display. However, the basemap  does not appear during printed (same result if i load this basemap as a layer or as a basemap).

Is this an issue or a configuration error ?

(Moreover I try to print osm basemap according to the documentation without result. (http://docs.3liz.com/fr/publisher_guide/advanced_lizmap_config.html#allow-printing-of-external-baselayers)

**Comment by antoine373** [comment] 2016-01-08 14:01
Hi,
I have the exactly the same issue as you.
My basemap layers are working well for display but nothing appear when i want to print it.
Just as you I can print it normally in other project

Have you suceed to fix it ? I'm really running out of idea....

**Comment by geoek** [comment] 2016-01-08 15:07
Hi,
No, i didn't find a solution to this issue. Always impossible to print a basemap in a child project.

However, i can now print osm basemap. But it does not work with google basemap (if you create a group with name "google-satellite", nothing is printed) (it's ok with osm and ign basemap)

**Comment by antoine373** [comment] 2016-01-11 08:50
OK, that's a really strange behaviour of lizmap.

What is your configuration ?
Mine : 
Lizmap 2.12.2
Lizmap plugin 2.0
Qgis server 2.12.2
Qgis desktop 2.12.2

**Comment by geoek** [comment] 2016-01-11 09:08
My configuration :
QGis Desktop & Server : 2.8
Lizmap : tested with 2.12 and 3.0 Beta2 : same behaviour

**Comment by geoek** [comment] 2016-02-08 14:12
@antoine373 : Hi Antoine, did you find a solution for this issue ? I have still the same behaviour, and it prevents me to use the integrated layers.

**Comment by antoine373** [comment] 2016-02-15 09:22
Hi geoek, I didn't find any solution !! I'm still unable to explain this behaviour...

**Comment by rldhont** [comment] 2016-02-15 09:33
Hi @geoek and @antoine373,

It's probably a QGIS Server issue. Has you test a GetPrint Request directly on a QGIS- Server ?
If the result is the same in Lizmap and QGIS Server, the issue comes from QGIS Server.

**Comment by Gustry** [comment] 2020-05-06 07:27
@rldhont Is this issue still valid? As you are assigned yourself, I'm removing the "stale" label

**Comment by rmarzocchi84** [comment] 2020-05-06 16:44
I have a problem printing layer in group where the "group as unique layer" is checked: 

![image](https://user-images.githubusercontent.com/4061154/81204474-87eee400-8fc9-11ea-866c-450d480e0851.png)

LWC 3.3.5
QGIS Server 3.10.6

**Comment by rmarzocchi84** [comment] 2020-05-06 16:46
Perhaps the problem is in the print request

https://gishosting.gter.it/lizmap-web-client/lizmap/www/index.php/lizmap/service/?repository=comuneoffida&project=Webgis_Offida_PRG-CATAST&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetPrint&FORMAT=pdf&EXCEPTIONS=application/vnd.ogc.se_inimage&TRANSPARENT=true&SRS=EPSG:3004&DPI=100&TEMPLATE=Stampa_A4%2050000&map0:extent=2412953.788324,4752352.785212,2418553.922992,4757202.901844&map0:scale=25000&map0:**LAYERS=PRG,Vincolo_Idrogeologico**&map0:**STYLES=,predefinito**&LAYERS=PRG,Vincolo_Idrogeologico&STYLES=,predefinito&OPACITIES=255,255

**Comment by rldhont** [comment] 2020-05-07 10:41
@rmarzocchi84 in your case It's a QGIS Server 3.10 regression https://github.com/qgis/QGIS/issues/35107 and https://github.com/qgis/QGIS/pull/35277 I try to fix it but I found a segfault...

**Comment by rmarzocchi84** [comment] 2020-05-07 10:51
Many thanks @rldhont. Let me know if I can do something to help at least with test

**Comment by rldhont** [comment] 2020-07-06 16:09
the fix has been integrated in release-3_10 https://github.com/qgis/QGIS/pull/37425 and will be available in 3.10.8.

**Closed** 2020-07-06 16:10 UTC
Labels: QGIS Server, bug
