### ISSUE TITLE
Export rights

### ISSUE THREAD

**Issue by Cww7** [3liz/lizmap-web-client#1418] opened 2019-12-05 13:48 UTC
Hello,

Is it possible to modify the export rights for each layer ? I would activate  export features only for a table  and not for all the tables :

![image](https://user-images.githubusercontent.com/19794922/70240840-3f0ed700-176e-11ea-887f-c48f5e40267c.png)

**Comment by josemvm** [comment] 2019-12-05 14:06
https://github.com/3liz/lizmap-web-client/issues/499

**Comment by Cww7** [comment] 2019-12-06 09:21
Does it means that it is not possible actually ?

**Comment by gioman** [comment] 2019-12-07 19:20
> Does it means that it is not possible actually ?

it means that it has already been requested as a feature, if the feature request is not closed it means that it has not been implemented yet and so this ticket it a duplicate.

**Comment by Cww7** [comment] 2019-12-10 07:05
Thank you for your clarification @gioman

**Comment by laurentj** [comment] 2019-12-19 12:50
duplicate of #499

**Closed by laurentj** 2019-12-19 12:50 UTC
Labels: question
