### ISSUE TITLE
[Bug]: Permalink avec filtre n'applique pas le filtre

### ISSUE THREAD

**Issue by PhVdV** [3liz/lizmap-web-client#3284] opened 2022-10-17 08:40 UTC
### What is the bug?

L'utilisation du Permalink pour lequel un filtre a été spécifié n'applique pas le filtre 

### Steps to reproduce the issue

1; Lizmap web : Open Data table
2: remplir la fenêtre du query 
3: outil de sélection
4: application du filtre
5: outil permalink
6: ouverture du permalink

### Versions

Qgis Serveur 3.18
Lizmap web client 3.4.4
Lizmap pluging 3.4

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.18

### Operating system

Server Ubuntu; client Win 10

### Browsers

Chrome

### Browsers version

Chrome 106

**Comment by Gustry** [comment] 2022-10-17 08:52
> Lizmap web client 3.4.4
Lizmap plugin 3.4

Both versions are too old. You should do the ticket template by following steps in the Lizmap QGIS desktop plugin next time.

I think this ticket is a duplicate of https://github.com/3liz/lizmap-web-client/issues/2552 ? Can you check on Lizmap Web Client 3.6 RC 1 ?

**Comment by nboisteault** [comment] 2022-12-08 09:52
This is not a bug but a feature that could be developed if funded. Relevant issue is https://github.com/3liz/lizmap-web-client/issues/2552

**Closed by nboisteault** 2022-12-08 09:52 UTC
Labels: bug, user interface, map viewer, regression

**Comment by PhVdV** [comment] 2022-12-08 13:45
It will also be necessary to provide funding to update the doc.

https://docs.lizmap.com/current/fr/user/attribute_table.html

![image](https://user-images.githubusercontent.com/72783461/206461679-b51db5f1-d44a-487a-a963-0f60213a9132.png)
