### ISSUE TITLE
[Bug]: Menu in browser changes to 'mobile' style

### ISSUE THREAD

**Issue by mcomelli** [3liz/lizmap-web-client#2422] opened 2021-08-04 11:59 UTC
### What is the bug?

Menu in desktop device changes from default appearence (buttons on left, first picture) to 'mobile' (sandwich button on top, second picture)

![menu_1](https://user-images.githubusercontent.com/7116134/128175963-b19c5f4f-8654-4dbe-b45b-0504a6c56df5.png)
![menu_2](https://user-images.githubusercontent.com/7116134/128175967-23d2d64b-eb6f-455f-9c55-3732a7bb3be4.png)

### Steps to reproduce the issue

I see this behaviour after a long time the page is open and inactive.

### Lizmap version

3.4.3

### QGIS desktop version

3.20

### QGIS server version

3.20

### Operating system

Ubuntu 20.04

### Browsers

Firefox

### Browsers version

Firefox 91

**Comment by nboisteault** [comment] 2021-09-13 15:40
Can you reproduce this issue on another computer?

**Comment by mcomelli** [comment] 2021-09-13 18:08
> 
> 
> Can you reproduce this issue on another computer?

I don't know how to reproduce it, couldn't find any pattern causing the problem It happens sometimes.

**Comment by nboisteault** [comment] 2021-09-14 07:01
It happened on several different computer?

**Comment by mcomelli** [comment] 2021-09-14 07:22
> 
> 
> It happened on several different computer?

No, just one, using Firefox on Windows 10

**Comment by nboisteault** [comment] 2021-09-14 07:25
Ok so I close the issue but it can be reopened if the problem is reproduced on an other computer.
Thanks for your report.

**Closed by nboisteault** 2021-09-14 07:25 UTC
Labels: bug, feedback
