### ISSUE TITLE
LWC tools should respect the layers order defined by the plugin

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#491] opened 2017-02-07 11:10 UTC
- locate layer
- attribute table
- tooltip layers
- selection
...

it seems to me that the layers order is random within the respective tools dock...

**Comment by josemvm** [comment] 2017-02-07 11:24
moreover, in the case of the tooltip the first layer of the list could be the default layer (*) to be displayed on the tool dock

(*) or there is a possibility in the plugin to set the default layer

**Comment by mdouchin** [comment] 2017-05-18 05:24
order respected for 

- [ ] edition
- [ ] attribute table
- [ ] locate by layer
- [ ] tooltip layers
- [ ] selection

**Comment by josemvm** [comment] 2017-09-04 08:24
hi @mdouchin @rldhont 

could you please fixe the next item (or items)?
is very useful when it comes to an extensive and thematic variety list

thank you in advance for your support

**Comment by josemvm** [comment] 2018-01-09 10:28
hi

please, could you fixe the next item (**attribute table**)?
it's very useful for organizing the layers list by themes

thanks in advance

**Comment by josemvm** [comment] 2018-06-06 09:01
just for remember you @rldhont @mdouchin :-)

**Comment by nboisteault** [comment] 2018-09-28 16:04
@josemvm layers order in attribute table works ok for me. Can you test ?

**Comment by josemvm** [comment] 2018-10-01 08:51
hi @nboisteault 

look at montpellier project:

![imagem](https://user-images.githubusercontent.com/10053874/46278800-264dd480-c55f-11e8-8cff-be8caf90ce67.png)

![imagem](https://user-images.githubusercontent.com/10053874/46278855-572e0980-c55f-11e8-817f-7d6e5d1ef66e.png)

thanks

**Comment by nboisteault** [comment] 2018-10-03 08:47
@josemvm You're right.
"attribute table" fixed by https://github.com/3liz/lizmap-web-client/pull/978.
Can you test it ?

**Comment by nboisteault** [comment] 2018-10-03 10:09
Locate by layer works thanks to this : https://github.com/3liz/lizmap-web-client/blob/bcf2a63e5ec552a46163cf2b5da851233fd867c9/lizmap/www/js/map.js#L2592

**Comment by nboisteault** [comment] 2018-10-03 13:32
Layer order in every tools has been fixed.
@josemvm : please test and tell us if it is ok. Thanks.

**Comment by josemvm** [comment] 2018-10-03 14:46
thank you so much @nboisteault 
everythin works fine!!! :-)

if you can take a look at time manager tool...

**Comment by josemvm** [comment] 2018-10-04 07:43
hi @nboisteault 

no, that's all!
go ahead on time manager and dataviz module 👍 

thanks

**Comment by rmarzocchi84** [comment] 2019-09-23 13:46
There is a problem in the edition tool because of the order key is interpreted as string and not as numeric value. 

So if you have 
0, 1, 2 [..], 10 
in the txt file

the online order is
0,1,10,11..,2,20, etc.

**Comment by josemvm** [comment] 2020-03-25 10:41
@nboisteault you have a regression here https://github.com/3liz/lizmap-web-client/pull/1552

**Comment by nboisteault** [comment] 2020-03-25 10:54
@josemvm please be more explicit...

**Comment by josemvm** [comment] 2020-03-25 10:58
@nboisteault sorry
in your enhanced selection tool, the layers list appears in a random order and not as given by creation order in lizmap plugin

**Comment by nboisteault** [comment] 2020-03-25 11:30
@josemvm I can't reproduce your issue.

**Comment by josemvm** [comment] 2020-03-25 11:40
@nboisteault please try here http://pdm-revisao.municipioarraiolos.pt/index.php/view/map/?repository=ma&project=queimasQueimadas

compare the layers order in table attributes with layers order in selection tool

check your mmailbox for credentials

**Comment by nboisteault** [comment] 2020-03-26 07:42
@josemvm Can you update Lizmap plugin and save your project ? The order should be updated in the cfg and be correct in LWC.

**Comment by nboisteault** [comment] 2020-03-26 07:52
@Gustry Can you confirm that Lizmap plugin saves in the cfg every layer in attribute table tab in the same order than visible ?

**Comment by nboisteault** [comment] 2020-03-26 07:58
@josemvm forget what I said I see the problem.

**Comment by nboisteault** [comment] 2020-03-26 08:41
@josemvm The issue should not happen when saving with the new version of Lizmap plugin but I added some code to assert correct behavior : https://github.com/3liz/lizmap-web-client/commit/75de4a38fcbb7094472e02f217fae1c617c97ef1

**Comment by josemvm** [comment] 2020-03-26 09:34
@nboisteault thanks
can you update the unstable release here https://packages.3liz.org/pub/lizmap/unstable/3.4/

**Comment by josemvm** [comment] 2020-03-26 10:37
everything is ok now! 👍

**Comment by nboisteault** [comment] 2020-06-11 12:58
@josemvm It seems order is respected for dataviz at least in master, can you confirm?

**Closed** 2023-07-18 14:34 UTC
Labels: bug, priority:low
