### ISSUE TITLE
basic layer option - "bug"?

### ISSUE THREAD

**Issue by morvan80** [3liz/lizmap-web-client#759] opened 2018-01-29 00:27 UTC
I tried with various versions of lizmap while putting in basic google-satellite layer options when I go to the repository I always see google-street in the foreground.
Do you have any suggestions to solve this bug?
Thank you

**Comment by josemvm** [comment] 2018-01-29 08:11
hi @morvan80 

see here: https://github.com/3liz/lizmap-web-client/issues/644

**Comment by josemvm** [comment] 2018-01-29 09:30
closed as duplicate of https://github.com/3liz/lizmap-web-client/issues/644

**Closed by josemvm** 2018-01-29 09:30 UTC
Labels: question

**Comment by morvan80** [comment] 2018-01-29 10:04
Hello, In the repository "without making changes" it works well the problem is when I have to choose in basic layer option putting Google Hybrid i always visualize Google Streets. Thanks for your time

Da: José Macau
Inviato: lunedì 29 gennaio 2018 10:30
A: 3liz/lizmap-web-client
Cc: morvan80; Mention
Oggetto: Re: [3liz/lizmap-web-client] basic layer option - "bug"? (#759)

Closed #759.
