### ISSUE TITLE
export layer to GeoJSON

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#278] opened 2016-04-01 08:41 UTC
hi,

after export a layer to GeoJSON format, i'm trying to load it into qgis desktop (2.14 or old versions) but only the attibute table is imported, the geometry doesn't appear!...

thanks

**Comment by nboisteault** [comment] 2016-04-01 09:39
If you open your file it in a text editor do you see geometry data?

**Comment by josemvm** [comment] 2016-04-01 09:55
hi Nicolas,

yes i can see the geometry information about my 2 points:

{"type": "FeatureCollection",
 "bbox": [ 16846.937499, -96437.8984385, 17288.093751, -95938.187499],
 "features": [
  {"type": "Feature",
   "id": "ponto_inicio.15",
 "bbox": [ 16849.12242977, -96435.41695063, 16849.12242977, -96435.41695063],
  "geometry": {"type": "Point", "coordinates": [16849.12242977, -96435.41695063]},
   "properties": {
   }
  }
 ,{"type": "Feature",
   "id": "ponto_inicio.16",
 "bbox": [ 17285.91, -95940.67, 17285.91, -95940.67],
  "geometry": {"type": "Point", "coordinates": [17285.91, -95940.67]},
   "properties": {
   }
  }
 ]
}

**Comment by nboisteault** [comment] 2016-04-01 11:53
Do you have a projection? Look at "crs" or "srs" in your file.

**Comment by josemvm** [comment] 2016-04-01 14:05
in fact the GeoJSON exported file throught the LizMap doesn't contain srsName/EPSG information unlike GML exported file... i must set the right projection after loading in QGIS.

is it expected to be so?

thanks

**Comment by nboisteault** [comment] 2016-04-01 14:09
I don't think it is expected, it should be a bug.

**Comment by mdouchin** [comment] 2016-04-02 11:12
Lizmap uses QGIS Server WFS request to export the data. I close this bug here because it is related to QGIS Server, not Lizmap which only acts as a proxy. Please report in qgis-dev mailing list and open an issue in hub.qgis.org with data to help reproduce it.

**Closed by mdouchin** 2016-04-02 11:12 UTC

**Comment by josemvm** [comment] 2016-04-10 18:39
http://hub.qgis.org/issues/14609

**Comment by josemvm** [comment] 2016-05-09 11:45
fixed in changeset http://hub.qgis.org/projects/quantum-gis/repository/revisions/9ea56acde03ace5c078c3d95f98be267eb1c22fd
