### ISSUE TITLE
Popup only on filtered layer

### ISSUE THREAD

**Issue by CorentinLemaitre** [3liz/lizmap-web-client#2258] opened 2021-04-30 16:20 UTC
### Is your feature request related to a problem? Please describe
When i use the filter side bar (filter data with form) I could choose to see only some features of my layer (points). When i click on a point i get a pop-up not only for the point showed in the map but also for the features exclude by the filter. 

Here is an example where i filter out the point id 230 and i get still information about this point in the popup.
![chrome-capture (1)](https://user-images.githubusercontent.com/20289907/116723755-1a10a900-a9e0-11eb-9813-db6a30821ae8.gif)

### Describe the solution you'd like
I would like that the popup show information only for the visible features in the map based on the layer.

**Comment by nboisteault** [comment] 2023-05-16 07:54
Thank you for reporting.
I close as it is a duplicate of https://github.com/3liz/lizmap-web-client/issues/1417

**Closed by nboisteault** 2023-05-16 07:54 UTC
Labels: enhancement, map viewer, popup, filter forms
