### ISSUE TITLE
lizmap base url

### ISSUE THREAD

**Issue by gcalibris** [3liz/lizmap-web-client#1366] opened 2019-10-28 12:39 UTC
Talking about lizmap wms, the base url address is 
```
http://sitename.com/lizmap_maps/index.php/lizmap/service/?
```
After the symbol "?" everything is going like parameters. So repository and project is like parameter. The question is: is any way to do that 
```
http://sitename.com/lizmap_maps/index.php/lizmap/service/?repository=repo_name&project=project_name
```
would be like base url, that repository and project would not be parameters.

**Comment by laurentj** [comment] 2019-11-12 13:28
duplicate of #14

**Closed by laurentj** 2019-11-12 13:28 UTC
