### ISSUE TITLE
[Bug]: Cannot see PG layers from in Lizmap Web Client (but i see the same layers trough QGIS Desktop)

### ISSUE THREAD

**Issue by AntonioCosti** [3liz/lizmap-web-client#3998] opened 2023-12-04 06:29 UTC
### What is the bug?

Hi dears,
i cannot see PG layers from in Lizmap Web Client (but i see the same .
layers trough QGIS Desktop).

I'm a newbe so please can someone suggest me a clear procedure to check the communication from my project on Lizmap and my server Postgis?

Antonio

### Steps to reproduce the issue

nn

### Versions

<html>
<body>
<h3 style="margin: 10px 0px; font-family: arial; font-weight: normal !important; line-height: 40px; color: rgb(51, 51, 51); text-rendering: optimizelegibility; font-size: 24.5px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(239, 239, 239); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Lizmap Web Client</h3><h4 style="margin: 10px 0px; font-family: arial; font-weight: normal !important; line-height: 20px; color: rgb(51, 51, 51); text-rendering: optimizelegibility; font-size: 17.5px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(239, 239, 239); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Information</h4>
Version | 3.6.6
-- | --
2023-10-04
http://...

</body>
</html>Lizmap Web Client
Information
Version	3.6.6
Date	2023-10-04
URL in the QGIS desktop plugin	http://qgis01.sirnet.it/lizmap36/lizmap/www/
QGIS Server
Version
Number	[3.28.12](https://github.com/qgis/QGIS/releases/tag/final-3_28_12)
Name	Firenze
Commit ID	[dcc633b2de](https://github.com/qgis/QGIS/commit/dcc633b2de)
Py-QGIS-Server	not used
Plugins
Plugin	Version
atlasprint	[3.3.2](https://github.com/3liz/qgis-atlasprint/releases/tag/3.3.2)
Lizmap server	[2.8.1](https://github.com/3liz/qgis-lizmap-server-plugin/releases/tag/2.8.1)
wfsOutputExtension	[1.8.0](https://github.com/3liz/qgis-wfsOutputExtension/releases/tag/1.8.0)

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.28.12

### Operating system

Windows Server 2022

### Browsers

Chrome

### Browsers version

Version 119.0.6045.200 (Official Build) (64-bit)

**Comment by Gustry** [comment] 2023-12-04 07:37
You should follow the ticket template, with the steps in QGIS desktop, Lizmap plugin. This will give us your plugin version etc. Check any update in the QGIS plugin manager.

**Comment by AntonioCosti** [comment] 2023-12-04 08:51
Really as a newbe i don't know exactly, i have followed this procedure: https://github.com/NaturalGIS/qgis_server_and_lizmap_on_windows and leaved as default, so i think the mode is PROD. 

Related to the safeguard i dont know where i must check to see it.

Antonio

**Comment by Gustry** [comment] 2023-12-04 09:44
The second one is "Prevent PostgreSQL from using a service file", right ?
So you kept the "Prevent PostgreSQL the QGIS auth db" ?

Why do you uncheck PGService file ? Did you use a service ? If yes, did you configure the PG Service on the server side as well ?

**Comment by AntonioCosti** [comment] 2023-12-04 19:21
Hi dear,
i have configured the service_pg and i see the DB connection from QGIS (working fine), in Safeguard i have select normal and unchecked all the flags but the problem still persist.. :(

**Comment by Gustry** [comment] 2023-12-05 07:22
> I'm a newbe so please can someone suggest me a clear procedure to check the communication from my project on Lizmap and my server Postgis?

>  in Safeguard i have select normal and unchecked all the flags but the problem still persist.. :(

Unchecking all checkbox, not using beginner mode, it means you are an "expert" and you know how your server is installed.

The beginner mode is exactly for this use case.
For instance, you could try your project without a PG service (as it requires some settings on the server, have you done it ?), check your QGIS server logs (Maybe some logs saying it can't connect to the database with "service unknown ?"), did you try to launch a PSQL console on the server and see if the service is recognized ?

I'm closing because it's not a bug.
Please have a look to pinned ticket https://github.com/3liz/lizmap-web-client/issues/1638

**Closed by Gustry** 2023-12-05 07:22 UTC
Labels: question, feedback
