### ISSUE TITLE
Adding operators to the selection and filter functionalties in the attribute table

### ISSUE THREAD

**Issue by saeri-ims** [3liz/lizmap-web-client#1273] opened 2019-06-26 14:51 UTC
### Is your feature request related to a problem? Please describe
I am trying to select from the same attribute table monument types and historical period. In QGIS I would simply use the expression monument_types = 'residential' AND historical_period = 1982
However i noticed that in lizmap when i apply a selection based on one value e.g. monument type and then i apply the filter i cannot carry on from this first selection and select period = 1982.

### Describe the solution you'd like
I would like to have the opportunity to have at least the simple operators such as AND, OR, LIKE, IS, NOT, >, <, >=, <= 

### Describe alternatives you've considered
At the moment the temporary solution is to merge the data into a new field so that i have monument types and period together and run the selection/filter on that column.
e.g. residential 1982
It is not elegant and will not be always applicable but for the time being allows me to give the users what they need.

### Additional context
I am a keen user and promoter of Lizmap and i am very thankful and grateful for all the work the developers are doing. I am aware that for QGIS3 there is a new filter functionality and it is great to see it. So, it would be great to see this enhancement happening in the future, as it will make the selection more useful for the general users.

**Comment by nboisteault** [comment] 2019-07-25 16:22
Duplicate of #762

**Closed by nboisteault** 2019-07-25 16:22 UTC
