### ISSUE TITLE
[Bug]: Filtering does not prevent to open popup on hidden features

### ISSUE THREAD

**Issue by vlebert** [3liz/lizmap-web-client#3584] opened 2023-04-03 13:29 UTC
### What is the bug?

When using the filtering widget, you can still open the popup of a hidden feature when clicking it's position.

### Steps to reproduce the issue

Set up a filter 

filter feature in Lizmap web client 

click on a hidden feature

### Versions

Versions :

 Lizmap Web Client : 3.6.3-pre.6077
 Lizmap Web Client target version : 3.6
 Lizmap plugin : 3.11.0
 QGIS Desktop : 3.22.8
 Lizmap.com : Yes
 QGIS Server : 3.22.16
 Py-QGIS-Server : 1.8.7
 QGIS Server plugin atlasprint : 3.3.2
 QGIS Server plugin cadastre : 1.17.3
 QGIS Server plugin lizmap_server : 2.7.0
 QGIS Server plugin wfsOutputExtension : 1.7.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Macos

### Browsers

Chrome

### Browsers version

Version 0.96.0 (38004)

**Comment by tethysgeco** [comment] 2023-05-05 13:35
Hello,
we can confirm this bug (lizmap 3.6.3, qgis server 3.28. plugin last release).
This behaviour can be critical for the final users (wrong data can be associated with the filtered geometry).
This happens both filtering data from the specific tool and from the attribute table.
In the past filtering data directly from the attribute table worked correctly and the popup of hidden geometry didn't open.

Let us know if we can help you in some way.
Thank you

**Comment by nboisteault** [comment] 2023-05-16 07:35
Thank you for reporting this issue.
I close as it is a duplicate of https://github.com/3liz/lizmap-web-client/issues/2258

**Closed by nboisteault** 2023-05-16 07:35 UTC
Labels: bug, map viewer, popup, filter forms
