### ISSUE TITLE
SQLite3::query(): Unable to prepare statement: 1, no such table: lizmap_search

### ISSUE THREAD

**Issue by gcalibris** [3liz/lizmap-web-client#1546] opened 2020-02-26 13:44 UTC
How to fix it:
SQLite3::query(): Unable to prepare statement: 1, no such table: lizmap_search	/lizmapwebclient/lib/jelix/plugins/db/sqlite3/sqlite3.dbconnection.php	112

This log happens when opening project at first time. 

 - Lizmap version: 3.3.0
 - QGIS Server version: 3.4.15
 - QGIS Project version: 3.4.15
 - OS (Windows, Linux, MacOS, Android…): Ubuntu
 - Browser (Firefox, Chrome…): Firefox, Chrome

**Comment by nboisteault** [comment] 2020-02-27 13:54
Duplicate of #1285

**Closed by nboisteault** 2020-02-27 13:54 UTC
Labels: bug
