### ISSUE TITLE
Layers visible only for selected users

### ISSUE THREAD

**Issue by bgisb** [3liz/lizmap-web-client#1107] opened 2019-03-13 15:37 UTC
Hi Guys!

Is it possible for not signed users to see 3 layers from the project and for logged users 10 layers from the same project? I'm afraid that filtering by the user will not solve the problem because the attribute table for 10 layers will be still visible.

I would like some of the layers in the project to be visible only to the group of administrators.

**Comment by rldhont** [comment] 2019-03-14 14:51
Not yet

**Comment by bgisb** [comment] 2019-03-14 16:24
Thank you for a quick reply.

**Comment by laurentj** [comment] 2019-03-18 15:46
duplicate of #1112

**Closed by laurentj** 2019-03-18 15:46 UTC
Labels: enhancement
