### ISSUE TITLE
PostgreSql connection not working

### ISSUE THREAD

**Issue by baradgeo** [3liz/lizmap-web-client#1658] opened 2020-05-28 04:57 UTC
When I set in profiles.ini.php
```ini
[jdb:jauth]
driver=sqlite3
database="var:db/jauth.db"

[jdb:lizlog]
driver=sqlite3
database="var:db/logs.db"
```
then everything woking fine, except the map using postGIS connection is not loading.

Then I change to this to get pgsql connection
```ini
[jdb:jauth]
driver="pgsql"
database="testqgis"
host="localhost"
port="5432"
user="postgres"
password="*****"

[jdb:lizlog]
driver="pgsql"
database="testqgis"
host="localhost"
port="5432"
user="postgres"
password="*****"
```
Now i am getting a error..

> "Error 500. A technical error has occured. Sorry for this trouble."

Please help.

**Comment by ygorigor** [comment] 2020-05-28 07:19
@baradgeo try to look in postgresql logs, maybe you will find some info

**Comment by Gustry** [comment] 2020-05-28 07:33
What are you trying to do:
* To have postgis layers working?
* AND/OR having lizmap internal tables in postgresql?

What you are doing above is changing the location of Lizmap internal tables.
IIRC, these kind of settings need to be changed before the install. You might need to check that.
On an existing install, I heard of a kind of migrator from sqlite to postgresql.

If you want to make postgresql layer working, this is not this fix.

**Comment by baradgeo** [comment] 2020-05-28 08:22
> What are you trying to do:
> 
> * To have postgis layers working?
> * AND/OR having lizmap internal tables in postgresql?
> 
> What you are doing above is changing the location of Lizmap internal tables.
> IIRC, these kind of settings need to be changed before the install. You might need to check that.
> On an existing install, I heard of a kind of migrator from sqlite to postgresql.
> 
> If you want to make postgresql layer working, this is not this fix.

To have postgis layers working?..... I want to do this. But don't know how. Can you please help?

**Comment by Gustry** [comment] 2020-05-28 08:35
So I think you rollback your profiles files, these settings **are not** for postgresql layers.
Duplicate of #1638

**Closed by Gustry** 2020-05-28 08:35 UTC
Labels: question
