### ISSUE TITLE
[Question]: Lizmap no longer renders layers on the map

### ISSUE THREAD

**Issue by sgalvi** [3liz/lizmap-web-client#4065] opened 2024-01-12 09:03 UTC
### What is the question?

![Screenshot from 2024-01-12 09-54-43](https://github.com/3liz/lizmap-web-client/assets/153731136/2778fefd-2377-4716-b287-6ef8e992c7b5)
Lizmap no longer shows me the layers on the map, with no project. Has this happened to anyone else?

### Versions

Qgis 3.28.11
Lizmap 3.7.0

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

ubuntu 20.04

### Browsers

Firefox

### Browsers version

121

**Comment by aeduard** [comment] 2024-01-12 11:39
I've just updated an installation from 3.6.8 to 3.7.0 and I have the same issue. Layer thumbnails, legend etc... is loaded, but nothing is visible on the map beside the basemaps.

**Comment by nworr** [comment] 2024-01-12 16:41
can it be related to issue #4027 ?

**Comment by sgalvi** [comment] 2024-01-15 09:28
I don’t think, in my case it doesn’t load any layer. However, the fact is completely random: it loads some projects for me always, others it doesn’t load at all. Others it loads first and then it doesn’t load them anymore.

**Comment by Gustry** [comment] 2024-01-15 09:54
You should check your QGIS server logs, you should see incoming WMS GetMap request and see there are any tips/warnings.

**Comment by sgalvi** [comment] 2024-01-15 10:35
It only gives me this error here: “QFont::fromString: Invalid description ‘(empty)’” but I don’t think it matters

**Comment by Gustry** [comment] 2024-01-15 10:48
Do you see request from your web browser to QGIS server ? Is the result of tiles OK ? HTTP 200 without empty content ?

**Comment by aeduard** [comment] 2024-01-15 12:05
I've also reinstalled v 3.7.0 to help debugging.
This is one line of the server log (I've changed project specific data to xxx):
`x.x.x.x - - [15/Jan/2024:13:50:49 +0200] "GET /lizmap/index.php/lizmap/service?repository=xxx&project=xxx&REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&FORMAT=image%2Fpng&STYLES=default&TRANSPARENT=true&LAYERS=xxx_1&DPI=112.5&WIDTH=2777&HEIGHT=1310&CRS=EPSG%3A3844&BBOX=265473.8459270772%2C620694.4164362514%2C271351.84101640066%2C623467.2553152625&ts=1705319636488 HTTP/1.1" 200 14689 "https://xxx/lizmap/index.php/view/map?repository=xxx&project=xxx" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"`

What I see different and it may be a problem with my server/apache configuration, that I see a lot more details in the web browser's address bar, e.g. when I activate a layer it's name appears in the address bar.

**Comment by ygorigor** [comment] 2024-01-15 12:11
Try to add an empty baselayer and see if your data will be rendered on it.
I have the same issue. On empty baselayer I can see all my data.

**Comment by aeduard** [comment] 2024-01-15 13:17
@ygorigor I've tried with empty baselayer, only one postgresql layer and without setting anything at baselayers, but nothing loads on the map. The layers pane is active and symbology is loaded well.
@Gustry Data sources are available, if I reinstall 3.6.7 it works. I don't know how to check if it is an empty tile. Also my qgis server logging is not ok, I have to check the settings.

**Comment by Gustry** [comment] 2024-01-15 13:24
> I don't know how to check if it is an empty tile

In your developer tools on your webbrower (F12), Network tab, by hovering your mouse on the request on the Javascript console, or open in a new tab this URL.

**Comment by sgalvi** [comment] 2024-01-15 14:31
ok now it doesn’t load anymore and responds with this.
![Screenshot from 2024-01-15 15-29-28](https://github.com/3liz/lizmap-web-client/assets/153731136/5291cc5c-4b6f-4109-a637-ce07abb49d4f)

**Comment by Gustry** [comment] 2024-01-15 14:46
Can you go in the "Network" tab ? and give us some details failing HTTP requests ?

**Comment by sgalvi** [comment] 2024-01-15 14:52
sure!
![Screenshot from 2024-01-15 15-39-44](https://github.com/3liz/lizmap-web-client/assets/153731136/d91ef232-74bd-425a-bc23-0069d99d807b)

**Comment by Gustry** [comment] 2024-01-15 15:25
Please give us the detail on a failing request (in purple), if it's green it's OK.
I'm not sure what is happening on GitHub, but I can't click on your screenshot to open it to make it bigger.

**Comment by sgalvi** [comment] 2024-01-15 15:35
The get I had selected was red

![Screenshot from 2024-01-15 16-34-33](https://github.com/3liz/lizmap-web-client/assets/153731136/1451d2b0-6f6d-4d41-9ed4-e9f17b52898f)
![Screenshot from 2024-01-15 16-34-29](https://github.com/3liz/lizmap-web-client/assets/153731136/60b80302-7e1d-4f40-8689-3710d2f42b97)
![Screenshot from 2024-01-15 16-34-04](https://github.com/3liz/lizmap-web-client/assets/153731136/cc9e6c68-e1ca-4b8a-ae7a-54690c2a5e35)

**Comment by aeduard** [comment] 2024-01-15 21:33
I'm also testing...I don't get any error on browsers console or network. In qgis-server log file, while it was set 1 for log level, I've got one line for each qgis request (eg. zooming on the map):
`23:15:40 WARNING Server[1454]: Error parsing post data as XML: at line 1, column 1: error occurred while parsing element. Assuming urlencoded query string sent in the post body.`
At the beginning of the log file I also have:
`23:15:40 WARNING Server[1454]: Invalid cache strategy, expecting 'filesystem', 'periodic' or 'off'. Using 'filesystem' as default.`

Then setting log level to 0, for one request I've got a so many lines in the log, as I've checked most of them are settings of the system. I'm posting it slightly edited, removing user details, if any other sensible data is preserved in the copied log file pls let me know.
```
23:17:48 INFO Server[1528]: QGIS Server Starting : 3.28.14-Firenze (b09131c5125)
23:17:48 INFO Server[1528]: QGIS Server Settings: 
23:17:48 INFO Server[1528]:   - QGIS_OPTIONS_PATH / '' (Override the default path for user configuration): '' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_PARALLEL_RENDERING / '/qgis/parallel_rendering' (Activate/Deactivate parallel rendering for WMS getMap request): 'false' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_MAX_THREADS / '/qgis/max_threads' (Number of threads to use when parallel rendering is activated): '-1' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_LOG_LEVEL / '' (Log level): '0' (read from ENVIRONMENT_VARIABLE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_LOG_FILE / '' (Log file): '/var/log/qgis/qgislog.txt' (read from ENVIRONMENT_VARIABLE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_LOG_STDERR / '' (Activate/Deactivate logging to stderr): 'false' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_PROJECT_FILE / '' (QGIS project file): '' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_IGNORE_BAD_LAYERS / '' (Ignore bad layers): 'false' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_CACHE_DIRECTORY / '/cache/directory' (Specify the cache directory): '//.local/share/QGIS/QGIS3/profiles/default/cache' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_CACHE_SIZE / '/cache/size' (Specify the cache size): '268435456' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_SHOW_GROUP_SEPARATOR / '/locale/showGroupSeparator' (Show group (thousands) separator): 'false' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_OVERRIDE_SYSTEM_LOCALE / '/locale/userLocale' (Override system locale): '' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_WMS_MAX_HEIGHT / '/qgis/max_wms_height' (Maximum height for a WMS request. The lower one of this and the project configuration is used.): '-1' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_WMS_MAX_WIDTH / '/qgis/max_wms_width' (Maximum width for a WMS request. The most conservative between this and the project one is used): '-1' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_API_RESOURCES_DIRECTORY / '/qgis/server_api_resources_directory' (Base directory where HTML templates and static assets (e.g. images, js and css files) are searched for): '/usr/share/qgis/resources/server/api' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_API_WFS3_MAX_LIMIT / '/qgis/server_api_wfs3_max_limit' (Maximum value for "limit" in a features request, defaults to 10000): '10000' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_TRUST_LAYER_METADATA / '' (Trust layer metadata): 'false' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_FORCE_READONLY_LAYERS / '' (Force to open layers in read-only mode): 'false' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_DISABLE_GETPRINT / '' (Don't load layouts): 'false' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_LANDING_PAGE_PROJECTS_DIRECTORIES / '/qgis/server_projects_directories' (Directories used by the landing page service to find .qgs and .qgz projects): '' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_LANDING_PAGE_PROJECTS_PG_CONNECTIONS / '/qgis/server_projects_pg_connections' (PostgreSQL connection strings used by the landing page service to find projects): '' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_LOG_PROFILE / '/qgis/server_log_profile' (Add detailed profile information to the logs, only effective when QGIS_SERVER_LOG_LEVEL=0): 'false' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_WMTS_SERVICE_URL / '/qgis/server_wmts_service_url' (The default WMTS service URL): '' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_OPTIONS_PATH / '' (): '' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_OPTIONS_PATH / '' (): '' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_OPTIONS_PATH / '' (): '' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_OPTIONS_PATH / '' (): '' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_LANDING_PAGE_PREFIX / '/qgis/server_landing_page_base_url_prefix' (Landing page base URL path prefix): '' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_PROJECT_CACHE_CHECK_INTERVAL / '/qgis/server_project_cache_check_interval' (The default project cache check interval): '0' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_PROJECT_CACHE_STRATEGY / '/qgis/server_project_cache_strategy' (Project's cache strategy. Possible values are 'off','filesystem' or 'periodic'): '' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]:   - QGIS_SERVER_ALLOWED_EXTRA_SQL_TOKENS / '/qgis/server_allowed_extra_sql_tokens' (List of comma separated SQL tokens to be added to the list of allowed tokens that the services accepts when filtering features): '' (read from DEFAULT_VALUE)
23:17:48 INFO Server[1528]: Ini file used to initialize settings: /.local/share/QGIS/QGIS3/profiles/default/QGIS/QGIS3.ini
23:17:48 INFO Server[1528]: cacheDirectory: /.local/share/QGIS/QGIS3/profiles/default/cache/
23:17:48 INFO Server[1528]: maximumCacheSize: 268435456
23:17:48 INFO Server[1528]: Prefix  PATH: /usr
23:17:48 INFO Server[1528]: Plugin  PATH: /usr/lib/qgis/plugins
23:17:48 INFO Server[1528]: PkgData PATH: /usr/share/qgis
23:17:48 INFO Server[1528]: User DB PATH: //.local/share/QGIS/QGIS3/profiles/default/qgis.db
23:17:48 INFO Server[1528]: Auth DB PATH: //.local/share/QGIS/QGIS3/profiles/default/qgis-auth.db
23:17:48 INFO Server[1528]: SVG PATHS: /usr/share/qgis/svg/://.local/share/QGIS/QGIS3/profiles/default/svg/
23:17:48 INFO Server[1528]: Adding service SampleService 1.0
23:17:48 INFO [1528]: Adding API Landing Page 
23:17:48 INFO Server[1528]: Adding service WCS 1.0.0
23:17:48 INFO Server[1528]: Adding service WFS 1.1.0
23:17:48 INFO Server[1528]: Adding service WFS 1.0.0
23:17:48 INFO [1528]: Adding API OGC WFS3 (Draft) 
23:17:48 INFO Server[1528]: Adding service WMS 1.3.0
23:17:48 INFO Server[1528]: Adding service WMS 1.1.1
23:17:48 INFO Server[1528]: Adding service WMTS 1.0.0
23:17:48 WARNING Server[1528]: Invalid cache strategy, expecting 'filesystem', 'periodic' or 'off'. Using 'filesystem' as default.
23:17:48 WARNING Server[1528]: Invalid cache strategy, expecting 'filesystem', 'periodic' or 'off'. Using 'filesystem' as default.
23:17:48 INFO Server[1528]: Initializing 'filesystem' cache strategy
23:17:48 INFO Server[1528]: Server initialized
23:17:48 INFO ./src/server/qgsserverplugins.cpp[1528]: load library /usr/lib/qgispython (3.28.14)
23:17:48 INFO ./src/server/qgsserverplugins.cpp[1528]: Python support library loaded successfully.
23:17:48 INFO WfsOutputExtension[1528]: WfsOutputExtension.__init__
23:17:48 INFO WfsOutputExtension[1528]: WfsOutputExtension : tempdir : /tmp/QGIS_WfsOutputExtension
23:17:48 INFO Server[1528]: Server plugin wfsOutputExtension loaded!
23:17:48 INFO Lizmap[1528]: Init server version "2.8.1"
23:17:48 INFO [1528]: Adding API Lizmap 2.8.1
23:17:48 INFO Lizmap[1528]: API "/lizmap" loaded with the server info handler
23:17:48 INFO Server[1528]: Adding service EXPRESSION 1.0.0
23:17:48 INFO Lizmap[1528]: Service "expression" loaded
23:17:48 INFO Server[1528]: Adding service LIZMAP 1.0.0
23:17:48 INFO Lizmap[1528]: Service "lizmap" loaded
23:17:48 INFO Lizmap[1528]: LizmapFilter.init
23:17:48 INFO Lizmap[1528]: Filter "lizmap" loaded
23:17:48 INFO Lizmap[1528]: Access control "lizmap" loaded
23:17:48 INFO Lizmap[1528]: Filter "get feature info" loaded
23:17:48 INFO Lizmap[1528]: Filter "get legend graphic" loaded
23:17:48 INFO Lizmap[1528]: Filter "legend on/off" loaded
23:17:48 INFO Server[1528]: Server plugin lizmap_server loaded!
23:17:48 INFO Server[1528]: Server python plugins loaded
23:17:48 INFO Server[1528]: ******************** New request ***************
23:17:48 INFO Server[1528]: Request URL: http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi
23:17:48 INFO Server[1528]: Environment:
23:17:48 INFO Server[1528]: ------------------------------------------------
23:17:48 INFO Server[1528]: SERVER_NAME: 127.0.0.1
23:17:48 INFO Server[1528]: REQUEST_URI: /cgi-bin/qgis_mapserv.fcgi
23:17:48 INFO Server[1528]: SCRIPT_NAME: /cgi-bin/qgis_mapserv.fcgi
23:17:48 INFO Server[1528]: REMOTE_ADDR: 127.0.0.1
23:17:48 INFO Server[1528]: SERVER_PORT: 80
23:17:48 INFO Server[1528]: QUERY_STRING: 
23:17:48 INFO Server[1528]: CONTENT_TYPE: application/x-www-form-urlencoded
23:17:48 INFO Server[1528]: REQUEST_METHOD: POST
23:17:48 INFO Server[1528]: SERVER_PROTOCOL: HTTP/1.1
23:17:48 WARNING Server[1528]: Error parsing post data as XML: at line 1, column 1: error occurred while parsing element. Assuming urlencoded query string sent in the post body.
23:17:48 INFO Lizmap[1528]: Request headers provided
23:17:48 INFO Lizmap[1528]: No lizmap user groups in request headers
23:17:48 INFO Lizmap[1528]: Lizmap user groups in parameters : admins
23:17:48 INFO Lizmap[1528]: Fetching /home/lizmap/test/test.qgs.cfg cfg file with last modified timestamp : 1705324038.0
23:17:48 INFO Lizmap[1528]: No acl defined in Lizmap config
23:17:48 INFO WfsOutputExtension[1528]: WfsOutputExtension.requestReady
23:17:48 INFO Server[1528]: BBOX:335430.546794,515324.479059,419171.339275,656215.385841
23:17:48 INFO Server[1528]: CRS:EPSG:3844
23:17:48 INFO Server[1528]: DPI:96
23:17:48 INFO Server[1528]: FORMAT:image/png
23:17:48 INFO Server[1528]: HEIGHT:1065
23:17:48 INFO Server[1528]: LAYERS:inv_collar
23:17:48 INFO Server[1528]: LIZMAP_OVERRIDE_FILTER:0
23:17:48 INFO Server[1528]: LIZMAP_USER:xxx
23:17:48 INFO Server[1528]: LIZMAP_USER_GROUPS:admins
23:17:48 INFO Server[1528]: MAP:/home/lizmap/test/test.qgs
23:17:48 INFO Server[1528]: REQUEST:getmap
23:17:48 INFO Server[1528]: SERVICE:WMS
23:17:48 INFO Server[1528]: STYLES:default
23:17:48 INFO Server[1528]: TRANSPARENT:true
23:17:48 INFO Server[1528]: VERSION:1.3.0
23:17:48 INFO Server[1528]: WIDTH:633
23:17:48 INFO AccessControlFilter[1528]: QgsAccessControlFilter plugin default layerPermissions called
23:17:48 INFO Lizmap[1528]: Request headers provided
23:17:48 INFO Lizmap[1528]: No lizmap user groups in request headers
23:17:48 INFO Lizmap[1528]: Lizmap user groups in parameters : admins
23:17:48 INFO Lizmap[1528]: Request headers provided
23:17:48 INFO Lizmap[1528]: No lizmap user login in request headers
23:17:48 INFO Lizmap[1528]: Lizmap user login in parameters : xxx
23:17:48 INFO Lizmap[1528]: Fetching /home/lizmap/test/test.qgs.cfg cfg file with last modified timestamp : 1705324038.0
23:17:48 INFO Lizmap[1528]: Lizmap config has no editionLayers
23:17:48 INFO Lizmap[1528]: No Lizmap layer group visibility for: inv_collar
23:17:48 INFO Server[1528]: WMS Request parameters:
23:17:48 INFO Server[1528]:  - CRS : EPSG:3844
23:17:48 INFO Server[1528]:  - WIDTH : 633
23:17:48 INFO Server[1528]:  - HEIGHT : 1065
23:17:48 INFO Server[1528]:  - BBOX : 335430.546794,515324.479059,419171.339275,656215.385841
23:17:48 INFO Server[1528]:  - LAYERS : inv_collar
23:17:48 INFO Server[1528]:  - STYLES : default
23:17:48 INFO Server[1528]:  - FORMAT : image/png
23:17:48 INFO Server[1528]:  - TRANSPARENT : true
23:17:48 INFO Server[1528]:  - DPI : 96
23:17:48 INFO Server[1528]:  - VERSION : 1.3.0
23:17:48 INFO Lizmap[1528]: Lizmap layerFilterSubsetString
23:17:48 INFO Lizmap[1528]: Request headers provided
23:17:48 INFO Lizmap[1528]: No lizmap override filter in request headers
23:17:48 INFO Lizmap[1528]: Lizmap override filter in parameters
23:17:48 INFO Lizmap[1528]: Request headers provided
23:17:48 INFO Lizmap[1528]: No lizmap user groups in request headers
23:17:48 INFO Lizmap[1528]: Lizmap user groups in parameters : admins
23:17:48 INFO Lizmap[1528]: Request headers provided
23:17:48 INFO Lizmap[1528]: No lizmap user login in request headers
23:17:48 INFO Lizmap[1528]: Lizmap user login in parameters : xxx
23:17:48 INFO Lizmap[1528]: Fetching /home/lizmap/test/test.qgs.cfg cfg file with last modified timestamp : 1705324038.0
23:17:48 INFO Lizmap[1528]: No editing context found in request headers
23:17:48 INFO Lizmap[1528]: No lizmap editing context filter in parameters : default value false
23:17:48 INFO Lizmap[1528]: Lizmap config has no loginFilteredLayers
23:17:48 INFO Lizmap[1528]: get_lizmap_layer_filter ran in 0.0s
23:17:48 INFO AccessControlFilter[1528]: QgsAccessControlFilter plugin default layerFilterSubsetString called
23:17:48 INFO AccessControlFilter[1528]: QgsAccessControlFilter plugin default layerFilterExpression called
23:17:48 INFO server[1528]: Parallel rendering deactivated
23:17:48 INFO WfsOutputExtension[1528]: WfsOutputExtension.responseComplete
23:17:48 INFO Server[1528]: Request finished in 172 ms
```

**Comment by sgalvi** [comment] 2024-01-16 08:29
I drop here the qgis log file. A message like this appears:
"QNetworkDiskCache::prepare() unable to open temporary file"
Temp files are saved in the default directory (/tmp).
The permissions with which the files are generated are as follows:
![Screenshot from 2024-01-16 09-26-53](https://github.com/3liz/lizmap-web-client/assets/153731136/b12f89c0-9941-41b9-b25d-21eaa8e0f2c8)

[error.log](https://github.com/3liz/lizmap-web-client/files/13947212/error.log)

I specify that I am using apache for the qgis server and nginx for lizmap.

**Comment by aeduard** [comment] 2024-01-18 05:28
I've tested with the new 3.7.1 version of lizmap and also lizmap_server plugin 2.8.2, the behavior remains the same, no layers are rendered beside base layers.

**Comment by nboisteault** [comment] 2024-01-18 09:39
Lizmap 3.7.2 will be released soon with a fix for this bug.

This bug occurs for big resolution display. You can use a workaround by using a bigger number here (4500 is enough for 4K displays) :

![image](https://github.com/3liz/lizmap-web-client/assets/2145040/8a2f6186-8b3e-4b74-bcdb-9a75dcfc979d)

**Comment by Gustry** [comment] 2024-01-18 10:19
> Lizmap 3.7.2 will be released soon with a fix for this bug. Sorry for this bug.

https://github.com/3liz/lizmap-web-client/releases/tag/3.7.2

**Comment by sgalvi** [comment] 2024-01-18 14:14
thank you!

**Comment by Gustry** [comment] 2024-01-18 14:19
thanks for the feedback

**Closed by Gustry** 2024-01-18 14:19 UTC
Labels: bug, feedback, map viewer

**Comment by aeduard** [comment] 2024-01-19 13:02
Sadly for me the issue is not resolved with 3.7.2 :(. I've tried also on smaller displays, like my phone. I've also raised _that_ number to 4500, but nothing helped. By the way I'm using two 2560 x 1440 resolution displays by default.
I've updated php from 8.1 to 8.2, restarted apache, also the whole server. I don't see anything new in the logs compared to my log posted 4 days ago. I've created a test project with a geopackage file to eliminate some eventual connection error to postgres. Not only vector data seems to not be visible, but also raster.
Any idea what should I try?

**Comment by nboisteault** [comment] 2024-01-19 13:08
@aeduard Maybe Ctrl + F5 on the map? Do you have any public link or portable project to share?

**Comment by aeduard** [comment] 2024-01-19 13:37
Yes I have a public test project, check below.
Now I did a fresh lizmap install without personal settings. I think I know what is the problem, it is somehow related to CRS. I've created a test project with randomly generated points saved into a geopackage (CRS 3844). Map also set to CRS 3844, nothing is rendered. If I change the map to 3857, than the points are visible. I've made these test projects public, you can check on the following page: [link](https://www.terragate.cloud/). The difference between the 2 maps is the map CRS and the adjusted map extents.

**Comment by aeduard** [comment] 2024-01-29 08:09
Could you test the issue with the CRS bug?

**Comment by nboisteault** [comment] 2024-02-06 14:10
I don't see any points in both maps. Please test with coming Lizmap 3.7.3 and open a ticket if issue still occurs.
