### ISSUE TITLE
nominatim external search not working

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#674] opened 2017-09-14 13:22 UTC
hi,

LWC nominatim search recently stop working:
![nominatim](https://user-images.githubusercontent.com/10053874/30431701-568625ec-9957-11e7-90d9-65f4bc1cc008.jpg)

the search engine for OSM is ok: https://nominatim.openstreetmap.org
![nominatim_osm](https://user-images.githubusercontent.com/10053874/30431811-b8289b54-9957-11e7-8572-63ecdea4cdf6.jpg)

**Comment by mdouchin** [comment] 2017-09-14 19:41
I can confirm this behaviour since 1 or 2 days, from many different users (with different servers). It seems Nominatim considers theses servers to override the number of requests (even on very new servers with low usage). 

A nominatim api bug or change in policy ?

**Comment by mdouchin** [comment] 2017-09-15 08:34
Fixed in d23abcb2 !

**Comment by josemvm** [comment] 2017-09-15 08:43
> change in policy

tested - ok

thanks for the great master! :-)

**Comment by rldhont** [comment] 2017-09-20 07:44
Fixed available in 3.1.4 https://github.com/3liz/lizmap-web-client/releases/tag/3.1.4 and 3.0.16 https://github.com/3liz/lizmap-web-client/releases/tag/3.0.16

**Closed by rldhont** 2017-09-20 07:44 UTC
Labels: bug
