### ISSUE TITLE
(graphical) selection tool: stop "button"

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#438] opened 2016-12-22 09:34 UTC
hi @rldhont,

the red cross (stop "button") doesn´t stop and close the tool just like all other tools

PS: the selection tool appears by default if you don't use the locating tool in yout project, i don´t know if it's on purpose...

**Comment by josemvm** [comment] 2016-12-30 11:17
on mobile devices the panel tool overlaps part of the main tool bar and the selections don't work properly

**Comment by rldhont** [comment] 2017-01-09 20:19
Can you open a specific issue for mobile ?
The issue is fixed in the 2 commits.

**Closed by rldhont** 2017-01-09 20:19 UTC
Labels: bug
