### ISSUE TITLE
Error server replied: Request-URI Too Long

### ISSUE THREAD

**Issue by pizzuga** [3liz/lizmap-web-client#1820] opened 2020-09-15 20:13 UTC
### Description
I've created a WFS service based on a PostgreSQL LineString table.
In both QGIS and Lizmap plugin I've enabled everyting, that is to say - create, modify, modify geometry and delete. Filtered by group according to a specific field of the table.

Following, part of the GetCapabilities for the layer:

```
<FeatureType>
  <Name>gao_tagliselettivi_2020_linestring</Name>
  <Title>gao_tagliselettivi_2020_linestring</Title>
  <SRS>EPSG:3003</SRS>
  <LatLongBoundingBox minx="1647416.48" maxx="1713820.625" miny="4807680.5" maxy="4884220.59"/>
  <Operations>
     <Query/>
     <Insert/>
     <Update/>
     <Delete/>
  </Operations>
</FeatureType>

```

After adding the WFS service to QGIS desktop (with a user belonging to an editor group), I can see and query data, and in some cases (the shortest lines) I can divide the line in two pieces, delete one of these and save my edits, but trying to do the same with the longest ones, QGIS throws an error that simply says something like "geometry not modify".

The Lizmap log reports:
2020-09-15 18:41:44	192.168.0.102	warning	2020-09-15 18:41:44	[2]	file_get_contents(http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?__httpbody=%3CTransaction+xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fwfs%22+service%3D%22WFS%22+version%3D%221.0.0%22+xmlns%3Agml%3D%22http%3A%2F%2Fwww.opengis.net%2Fgml%22+xmlns%3Axsi%3D%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema-instance%22+xsi%3AschemaLocation%3D%22http%3A%2F%2Fwww.qgis.org%2Fgml+http%3A%2F%2F192.168.0.41%2Fcb3mv%2Findex.php%2Flizmap%2Fservice%2F%3Frepository%3Dcb3mv%26amp%3Bproject%3Dstefanini%26amp%3BSERVICE%3DWFS%26amp%3BREQUEST%3DDescribeFeatureType%26amp%3BVERSION%3D1.0.0%26amp%3BTYPENAME%3Dgao_tagliselettivi_2020_linestring%22%3E%3CUpdate+xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fwfs%22+typeName%3D%22gao_tagliselettivi_2020_linestring%22%3E%3CProperty+xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fwfs%22%3E%3CName+xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fwfs%22%3Egeometry%3C%2FName%3E%3CValue+xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fwfs%22%3E%3Cgml%3ALineString+srsName%3D%22EPSG%3A3003%22%3E%3Cgml%3Acoordinates+cs%3D%22%2C%22+ts%3D%22+%22%3E1678813.35000000009313226%2C4844662.84999999962747097+1678812.91999999992549419%2C4844655.57000000029802322+1678811.96999999997206032%2C4844645.4599999999627471+1678809.21999999997206032%2C4844636.13999999966472387+1678805.7
....... 
....... a lot of coordinates 
....... 
1678201.96999999997206032%2C4839974.20000000018626451+1678203.25%2C4839964.26999999955296516+1678214.27035581972450018%2C4839892.49220392759889364%3C%2Fgml%3Acoordinates%3E%3C%2Fgml%3ALineString%3E%3C%2FValue%3E%3C%2FProperty%3E%3CFilter+xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fogc%22%3E%3CFeatureId+xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fogc%22+fid%3D%22gao_tagliselettivi_2020_linestring.797%22%2F%3E%3C%2FFilter%3E%3C%2FUpdate%3E%3C%2FTransaction%3E&amp;map=%2Fhome%2Fgisftp%2Fcb3mv%2Fstefanini.qgs&amp;service=WFS): failed to open stream: HTTP request failed! HTTP/1.1 414 Request-URI Too Long
	/opt/lizmap/lizmap/modules/lizmap/classes/lizmapProxy.class.php	241

Also the WFS log in QGIS reports: "server replied: Request-URI Too Long", so after a little googleing I've added the variable "LimitRequestLine 4000000" in the apache.conf file. After restarting apache2 the error warning in QGIS becomes more cryptic "server replied: Internal Server Error"

the same in Lizmap log:
2020-09-15 21:41:27	192.168.0.102	warning	2020-09-15 21:41:27	[2]	file_get_contents(http://127.0.0.1/cgi-bin/qgis_mapserv.fcgi?__httpbody=%3CTransaction+xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fwfs%22+service%3D%22WFS%22+version%3D%221.0.0%22+xmlns%3Agml%3D%22http%3A%2F%2Fwww.opengis.net%2Fgml%22+xmlns%3Axsi%3D%22http%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema-instance%22+xsi%3AschemaLocation%3D%22http%3A%2F%2Fwww.qgis.org%2Fgml+http%3A%2F%2F192.168.0.41%2Fcb3mv%2Findex.php%2Flizmap%2Fservice%2F%3Frepository%3Dcb3mv%26amp%3Bproject%3Dstefanini%26amp%3BSERVICE%3DWFS%26amp%3BREQUEST%3DDescribeFeatureType%26amp%3BVERSION%3D1.0.0%26amp%3BTYPENAME%3Dgao_tagliselettivi_2020_linestring%22%3E%3CUpdate+xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fwfs%22+typeName%3D%22gao_tagliselettivi_2020_linestring%22%3E%3CProperty+xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fwfs%22%3E%3CName+xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fwfs%22%3Egeometry%3C%2FName%3E%3CValue+xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fwfs%22%3E%3Cgml%3ALineString+srsName%3D%22EPSG%3A3003%22%3E%3Cgml%3Acoordinates+cs%3D%22%2C%22+ts%3D%22+%22%3E1678813.35000000009313226%2C4844662.84999999962747097+1678812.91999999992549419%2C4844655.57000000029802322+1678811.96999999997206032%2C4844645.4599999999627471+1678809.21999999997206032%2C4844636.13999999966472387+1678805.71999999997206032%2C4844627.00999999977648258
....... 
....... a lot of coordinates 
....... 
1678195.44999999995343387%2C4840024.16999999992549419+1678196.2900000000372529%2C4840019.07000000029802322+1678201.96999999997206032%2C4839974.20000000018626451+1678203.25%2C4839964.26999999955296516+1678210.88874354516156018%2C4839914.5173254581168294%3C%2Fgml%3Acoordinates%3E%3C%2Fgml%3ALineString%3E%3C%2FValue%3E%3C%2FProperty%3E%3CFilter+xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fogc%22%3E%3CFeatureId+xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Fogc%22+fid%3D%22gao_tagliselettivi_2020_linestring.797%22%2F%3E%3C%2FFilter%3E%3C%2FUpdate%3E%3C%2FTransaction%3E&amp;map=%2Fhome%2Fgisftp%2Fcb3mv%2Fstefanini.qgs&amp;service=WFS): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error
	/opt/lizmap/lizmap/modules/lizmap/classes/lizmapProxy.class.php	241

### Environment

The same occurs in two very different configurations:

qgis server 2.18, postgresql 11, lizmap 3.3.6-pre
qgis server 3.10, postgresql 12, lizmap 3.3.11-pre

Any idea?
[full_lizmap.log](https://github.com/3liz/lizmap-web-client/files/5228062/full_lizmap.log)

**Comment by rldhont** [comment] 2020-09-16 07:56
The request to QGIS Server by Lizmap has to be POST.

**Comment by xavyeah39** [comment] 2020-09-16 09:18
Same problem for me with popup display on layers trigger-filltered by an atlas (qgis relations). 
When related layers contains many entities, a 414 error Request too long is occur.
Partially solved by increasing Apache LimitRequestLine parameter.
Thanks,

**Comment by Gustry** [comment] 2020-10-26 12:57
@nboisteault Do you have some insights?

**Comment by nboisteault** [comment] 2020-10-26 13:53
We need to use POST and not GET everywhere it is possible in code. Changes have been made in some places yet.

**Comment by Gustry** [comment] 2020-10-26 13:57
Just curious, why 3.5.0 milestone ?
Is-it not a bug in existing release ? (especially 3.4 ?)

**Comment by mbernasocchi** [comment] 2021-04-07 11:39
we found the same issue in getprint when many layers are selected

**Comment by gioman** [comment] 2023-12-06 13:23
> We need to use POST and not GET everywhere it is possible in code. Changes have been made in some places yet.

@nboisteault is this still a thing also on LMWC 3.7? If yes is there any chance to have this fixed sooner than later (supporting the work to, of course)?

**Comment by gioman** [comment] 2023-12-06 16:45
> Did you get the issue ? Doing which request/action ?

@Gustry print/getprint after having added a KML > as it gets translated into a sequence of coordinated (WKT?) that is sent in the request, the URL gets quickly very long unless the geometries uploaded are very simple/few. I tried to workaround this at a web server level with the `LimitRequestLine `parameter but at no avail. As far as I understand the request must really be done via POST and not GET.

**Comment by gioman** [comment] 2023-12-07 09:23
@nboisteault here attached.

[teste5.zip](https://github.com/3liz/lizmap-web-client/files/13598103/teste5.zip)

**Comment by nboisteault** [comment] 2023-12-07 11:09
@gioman I achieved to print with your file. Maybe look at restrictions concerning POST requests?

**Comment by gioman** [comment] 2023-12-14 08:52
> @gioman I achieved to print with your file. Maybe look at restrictions concerning POST requests?

@nboisteault on what LMWC version have you tested? In other words, on what version that request has been changed to POST?

**Comment by nboisteault** [comment] 2023-12-14 15:31
@gioman I have tested on master but as far as I remember it should be ok with 3.6.

**Comment by Gustry** [comment] 2023-12-14 16:13
Hopefully, 3.6 will be EOL soon (we won't do long overlap like we did anymore).
If it's fixed in master and 3.7 branch, it's unlikely to have a patch on 3.6 because of the time frame.

**Comment by gioman** [comment] 2023-12-16 13:24
@Gustry @nboisteault I tried the kml I attached above with the test project I attach here on LMWC 3.7.0 and while it seems it loads at the correct extent it does not show on the map. Drawing manually works.

[nuts.zip](https://github.com/3liz/lizmap-web-client/files/13692695/nuts.zip)

Printing causes the very same error:

Request-URI Too Long

_The requested URL's length exceeds the capacity limit for this server._

![image](https://github.com/3liz/lizmap-web-client/assets/1951107/44d35ba2-c06e-403d-828a-84af7cc4143a)

**Comment by Gustry** [comment] 2023-12-16 15:19
Can you make a "Copy as CURL" in your webbrowser on the request ? (maybe cut  WKT strings if it's obviously too long)
It will help identify the specific request failing, with parameters.

**Comment by gioman** [comment] 2023-12-16 16:27
> Can you make a "Copy as CURL" in your webbrowser on the request ? (maybe cut WKT strings if it's obviously too long)
> It will help identify the specific request failing, with parameters.

[curl_lm_kml.zip](https://github.com/3liz/lizmap-web-client/files/13693158/curl_lm_kml.zip)

here attached. I wonder how @nboisteault was able to print the same kml. Maybe after this is just something that needs to be tuned at a web server level, question is... how?

**Comment by gioman** [comment] 2023-12-16 16:29
[curl_lm_kml.zip](https://github.com/3liz/lizmap-web-client/files/13693168/curl_lm_kml.zip)

**Comment by Gustry** [comment] 2023-12-16 16:35
Thanks, this is helping ... we can see the request is using POST as discussed in this ticket.
Then the issue is something else indeed.

**Comment by gioman** [comment] 2023-12-16 16:49
> Then the issue is something else indeed.

@Gustry right. Seems something we may want to document anyway (assuming that is something that needs to be tweaked on ngnix or apache), but anything I tried until now did not helped.

**Comment by gioman** [comment] 2023-12-16 18:44
> Then the issue is something else indeed.

@Gustry and it remains the issue that loading the provided KML is a no show on LMWC 3.7.0 canvas. Actually also a much simpler KML with just 4 vertices does not show, and now I realized that when they are loaded while LM does zoom at at certain extent it is not the correct one

[teste6.zip](https://github.com/3liz/lizmap-web-client/files/13693592/teste6.zip)

> but anything I tried until now did not helped.

for example: https://stackoverflow.com/a/2891598

**Comment by Gustry** [comment] 2023-12-18 11:58
> it remains the issue that loading the provided KML is a no show on LMWC 3.7.0

Importing KML is client side only, not linked to "request URI too long", right ? Please create a separate ticket to ease tracking different issues. There are some manual KML imports in tests : https://github.com/3liz/lizmap-web-client/tree/master/tests/qgis-projects/tests/test_import_kml

> [curl_lm_kml.zip](https://github.com/3liz/lizmap-web-client/files/13693168/curl_lm_kml.zip)

So it's a GetPrint URL. I'm not able to check all the content in the POST body, there are WKT and SVG inside, @nboisteault ?
Does the GetPrint works in curl ? (curiosity) (to check the transform from Curl, if it's was correct)
In the server, you should see a the error as well ? Mabe with higher debug level, you can see the full HTTP request coming ?
I was checking https://stackoverflow.com/questions/2880722/can-http-post-be-limitless

**Comment by gioman** [comment] 2023-12-19 19:01
> Importing KML is client side only, not linked to "request URI too long", right ? Please create a separate ticket to ease tracking different issue

@Gustry done here https://github.com/3liz/lizmap-web-client/issues/4035

**Comment by gioman** [comment] 2023-12-19 19:45
> Does the GetPrint works in curl ? (curiosity) (to check the transform from Curl, if it's was correct)

@Gustry 

`-bash: /usr/bin/curl: Argument list too long`

**Comment by gioman** [comment] 2023-12-19 19:50
> In the server, you should see a the error as well ? Mabe with higher debug level, you can see the full HTTP request coming ?

@Gustry this is the error, and is in the web sever log (nothing in QGIS or PHP log):

`[Tue Dec 19 20:47:46.044719 2023] [fcgid:warn] [pid 1953978] [client 95.216.214.125:53276] mod_fcgid: HTTP request length 139264 (so far) exceeds MaxRequestLen (131072)`

**Comment by gioman** [comment] 2023-12-19 20:01
Fixed with https://stackoverflow.com/questions/14066109/mod-fcgid-http-request-length-138520-so-far-exceeds-maxrequestlen-131072#comment69390156_18114711

**Comment by nboisteault** [comment] 2023-12-19 20:49
Thanks for feedback.

**Closed by nboisteault** 2023-12-19 20:49 UTC
Labels: bug
