### ISSUE TITLE
[Question]: Plot address search result on map?

### ISSUE THREAD

**Issue by norbythegeek** [3liz/lizmap-web-client#4961] opened 2024-11-08 21:58 UTC
### What is the question? (in English)

My address search seems to work, in that when I search for an address the map pans and zooms to the address I select.  But it doesn't show a little pin or point on the address found.  Is there a way to accomplish this?  A bit of Javascript, perhaps?  Or do I have something misconfigured?

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.8.2
* Lizmap plugin : 4.4.3
* QGIS Desktop : 3.38.3
* QGIS Server : 3.38.3
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : Not found
* QGIS Server plugin lizmap_server : 2.11.1
* QGIS Server plugin wfsOutputExtension : Not found

<details>
<summary>List of Lizmap Web Client modules :</summary>
<br/>
* Version Lizmap Web Client 3.8 needed
</details>

<details>
<summary>List of safeguards :</summary>
<br/>
* Mode : normal<br/>
* Allow parent folder : no<br/>
* Prevent other drive : yes<br/>
* Prevent PG service : yes<br/>
* Prevent PG Auth DB : yes<br/>
* Force PG user&pass : yes<br/>
* Prevent ECW : yes<br/>
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 22.04

### Browsers

Chrome, Microsoft Edge

### Browsers version

Edge 130.0.2849.68, Chrome 130.0.6723.117

**Comment by guenterw** [comment] 2024-11-09 12:20
I can confirm that. Seems to be a bug in V3.8.
In V3.7.12, the search result is highlighted in yellow:

![image](https://github.com/user-attachments/assets/6cd9f35c-65ed-43d9-a1c7-a6c8ff37b32c)

not in V3.8.3
![image](https://github.com/user-attachments/assets/4649a5af-4e1d-4db5-9420-9857c019e4c7)


Search for "Hauptstrasse 108, Herbolzheim" in
https://cx21-7.webgis.biz/index.php/view/map?repository=buergergis7&project=bauleitplanung_3_7
https://cx21-8.webgis.biz/index.php/view/map?repository=buergergis8&project=bauleitplanung_3_8

Setting in each case:
![image](https://github.com/user-attachments/assets/338aca88-6877-4257-9dc0-ad50fccdfa24)

**Comment by josemvm** [comment] 2024-11-10 20:35
maybe related with this https://github.com/3liz/lizmap-web-client/issues/4893

**Comment by Gustry** [comment] 2024-11-13 12:50
I think it's fixed in 3.8.3 with PR #4864 commit [b1de3fd](https://github.com/3liz/lizmap-web-client/pull/4864/commits/b1de3fdf6f3b8f6a73fdd50e0af9ce94da4e7f7c)

Can you confirm ?

**Closed** 2024-11-13 13:59 UTC
Labels: bug, feedback, map viewer

**Comment by guenterw** [comment] 2024-11-13 18:00
in version 3.8.4-pre it works again:

![image](https://github.com/user-attachments/assets/d421610a-4003-4727-9d7f-bdc8fd49d667)

Thanks for the quick correction
