### ISSUE TITLE
[Bug]: Can't open the edition due to JSON cache error on demo.lizmap.com

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-web-client#2428] opened 2021-08-11 15:03 UTC
### What is the bug?

I can't add a new feature : 

```
Can't read the Json form file, try to clear your cache and reload the page.
```

### Steps to reproduce the issue

On https://demo.lizmap.com/lizmap/index.php/view/map/?repository=feat1&project=observatoire

I can't add a new feature on the layer.

![Screenshot from 2021-08-11 16-57-42](https://user-images.githubusercontent.com/1609292/129053149-fea16b55-c2a8-47da-bc57-a1693c6f0d4c.png)

IMHO, the error message is not very explicit, especially for a final user.
And if there is no cache available, we should recompute it ?

### Lizmap version

demo.lizmap.com

### QGIS desktop version

demo.lizmap.com

### QGIS server version

demo.lizmap.com

### Operating system

Ubuntu 21.04 and Android

### Browsers

Firefox

### Browsers version

90.0.2

**Comment by mdouchin** [comment] 2021-08-11 15:16
Resolved by manually deleting the cache **server-side** (Redis cache) with Lizcloud instances management tools `clearcache` only for projects and rights

**Comment by Gustry** [comment] 2021-08-11 15:19
Thanks.

But IMHO, the message should more explicit for the UX : 
is-it the user fault or the administrator fault ? (browser cache or server cache)

If there is an error with the cache, the code should try to by-pass the cache ?

**Comment by laurentj** [comment] 2021-08-19 07:55
>But IMHO, the message should more explicit for the UX

This message is not supposed to appear. If it appears, 1) there is a bug in our code, 2) or the cache content is not consistent anymore and should be recreated. We could fix Lizmap to avoid the second case, but it requires to refactor the projects classes.

**Comment by rldhont** [comment] 2021-08-23 07:45
The issue is here https://github.com/3liz/lizmap-web-client/blob/release_3_5/lizmap/modules/lizmap/lib/Form/QgisForm.php#L106

**Comment by laurentj** [comment] 2021-08-25 08:21
PR : #2447

**Comment by laurentj** [comment] 2021-09-01 12:58
PR merged. It should be fixed.

**Closed by laurentj** 2021-09-01 12:58 UTC
Labels: bug, data editor
