### ISSUE TITLE
Loose multi-values when opened the edit form

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-web-client#2361] opened 2021-06-24 16:13 UTC
### What is the bug?
For a field with multi-values capabilities, the form does not display the already selected values for this field.

### Steps to reproduce the issue

1. Create a QGIS project with 1 editable postgis layer that already contains features
2. In the _Layer properties_ window, in the _Attributes form_ tab, for the multi-values field, choose _Value Relation_ as Edit widget and check _allow multiple selections_
3. Do the lizmap config
4. Enable edition capabilities for the postgis layer with Edit attributes and Edit geometry
5. Publish the map to Lizmap Web Client
6. Go to the map
7. Click on a feature
8. Click on Edit button
9. Check multiple values
10. Save
11. Click on the same feature, Click on Edit button
12. See that the saved multiple values are not displayed in the form

### Expected behavior
The form has to displayed the multiple-values by checking checkboxes.

### Environment

 - Lizmap Web Client version: 3.4.4
- QGIS Server FULL version: 3.10
- QGIS Desktop FULL version: 3.10
- OS (Windows, Linux, MacOS, Android…): All
- Browser (Firefox, Chrome…): All

### Reporter

Ville dAvignon

**Comment by nboisteault** [comment] 2021-06-30 08:30
@rldhont I can't reproduce the issue with a non spatial layer. I now test with a spatial one.

**Comment by nboisteault** [comment] 2021-06-30 08:39
It is ok with Lizmap 3.4.4 too.

**Comment by nboisteault** [comment] 2021-07-19 15:48
Fixed by 442bd50c3317636ad68d4e6f2dca6895863bc53a

**Closed by nboisteault** 2021-07-19 15:48 UTC
Labels: bug, data editor, regression
