### ISSUE TITLE
Allow download of raster

### ISSUE THREAD

**Issue by katagen** [3liz/lizmap-web-client#4741] opened 2024-09-10 13:27 UTC
### What is the question? (in English)

I have some maps, and I want « admin » to be able to download layers.
I have set the right for that! There is no problem to download « vector layers », but I don’t see the possibility if it is « raster layers »?!?

Is there a solution to download them?

### Versions, safeguards, check summary etc

QGIS server: 3.34.9
Lizmap web client 3.7.10

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 20.4

### Browsers

Firefox

### Browsers version

Firefox LTR

**Comment by gioman** [comment] 2024-09-11 08:49
@katagen duplicate of https://github.com/3liz/lizmap-web-client/issues/46 but I agree that it would really be nice to have it. I think that for file based rasters it would be nice to have the option to allow a direct download without any need of any translation/processing. In general (so to include also any other type of raster of vector source) the option missing is to allow export the map (anything visible) as a referenced raster, and this should be doable by exporting the image that has been already generated.

**Comment by Gustry** [comment] 2024-09-11 10:47
It's indeed not possible to do it "natively" but I indeed see some feature requests on this.
As a quick workaround, why not moving your raster layer in the `media` directory, and then put the link in the "Link" section of the layer in the QGIS desktop plugin ?

The link media is like `index.php/view/media/getMedia?repository=REPOSITORY&project=PROJECT&path=media%2Fexample%2Fraster.tiff`

https://demo.lizmap.com/lizmap/index.php/view/media/getMedia?repository=features&project=cats&path=media%2Fdata_cats%2Fbeluga.jpg
This is not perfect, not checking ACL for instance, or the layer can't be cropped.

Or you can use a native cloud format, like COG, and pu the URL of the COG in the "link" section as well and the layer will be cropped according the request.

Let's close this ticket here and continue the discussion in #46 indeed.

**Closed by Gustry** 2024-09-11 10:47 UTC
Labels: question

**Comment by gioman** [comment] 2024-09-11 13:05
> As a quick workaround, why not moving your raster layer in the `media` directory, and then put the link in the "Link" section of the layer in the QGIS desktop plugin ?

@Gustry yes, this is of course the obvious workaround, but the UX is not consistent with the vector download, for this reason I was suggesting that for file based raster datasources a consistent UI could be provided, allowing the direct download of the raster in its original form and format.

On top of it or as alternative, the option to export the canvas as a georeferenced raster (taking advantaged of QGIS Server GetMap of course) it would be even more important in my opinion.

**Comment by Gustry** [comment] 2024-09-11 14:05
That's why I said it was "quick workaround" ;-)
Using COG or media is not so obvious IMHO, just an quick idea.

I only closed this ticket, to keep the #46 ;-)

**Comment by gioman** [comment] 2024-09-13 12:09
> That's why I said it was "quick workaround" ;-)

@Gustry yes of course, I have understand that. I was just saying that the workaround is pretty obvious and works well but for sake of UX consistency a better solution would be welcome.

> I only closed this ticket, to keep the #46 ;-)

+1

**Comment by gioman** [comment] 2024-09-13 12:18
> Enjoy the contributor meeting if you are there ;-)

Not there unfortunately. But look forward for Sweden next June.
