### ISSUE TITLE
lizmap lost the ability to sort columns in table

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#3009] opened 2022-05-24 09:32 UTC
### What is the bug?

lizmap doesn´t respect the order in table given by qgis desktop

### Steps to reproduce the issue

check the inittial order, change the order and check again

### Versions

 Lizmap Web Client : 3.4.12-pre.4741
 Lizmap plugin : 3.7.7
 QGIS Desktop : 3.16.16
 QGIS Server and plugins unknown status because running Lizmap Web Client < 3.5

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.16.16

### Operating system

Ubuntu 20.04

### Browsers

Firefox

### Browsers version

100

**Comment by Gustry** [comment] 2022-05-24 11:32
Duplicate of #2780

**Closed by Gustry** 2022-05-24 11:32 UTC
Labels: bug, regression, attribute table
