### ISSUE TITLE
[Bug]: Lizmap webclient 3.6.1

### ISSUE THREAD

**Issue by WarpNine88** [3liz/lizmap-web-client#3486] opened 2023-02-15 07:02 UTC
### What is the bug?

```
2023-02-15 06:16:14	::1	error	The lizmap_server plugin needs to be updated.
2023-02-15 06:16:39	[2]	file_get_contents(C:\OSGeo4W\Lizmap\Prod\WebClient\lizmap/var/lizmap-theme-config/theme.css): Failed to open stream: No such file or directory	C:\OSGeo4W\Lizmap\Prod\WebClient\lizmap\vendor\jelix\jelix\lib\jelix\utils\jFile.class.php	40

2023-02-15 06:16:47	[2]	Undefined array key "metadata"	C:\OSGeo4W\Lizmap\Prod\WebClient\lizmap\modules\lizmap\lib\Server\Server.php	63

2023-02-15 06:16:47	[2]	Trying to access array offset on value of type null	C:\OSGeo4W\Lizmap\Prod\WebClient\lizmap\modules\lizmap\lib\Server\Server.php	63

2023-02-15 06:16:50	[2]	Undefined array key "metadata"	C:\OSGeo4W\Lizmap\Prod\WebClient\lizmap\modules\lizmap\lib\Server\Server.php	63

2023-02-15 06:16:50	[2]	Trying to access array offset on value of type null	C:\OSGeo4W\Lizmap\Prod\WebClient\lizmap\modules\lizmap\lib\Server\Server.php	63

2023-02-15 06:16:50	::1	error	QGIS Server needs to be updated at least to version 3.10 for this version of Lizmap Web Client.
2023-02-15 06:16:50	[2]	Undefined array key "plugins"	C:\OSGeo4W\Lizmap\Prod\WebClient\lizmap\modules\lizmap\lib\Server\Server.php	54

2023-02-15 06:16:50	[2]	Trying to access array offset on value of type null	C:\OSGeo4W\Lizmap\Prod\WebClient\lizmap\modules\lizmap\lib\Server\Server.php	54

2023-02-15 06:16:50	[2]	Trying to access array offset on value of type null	C:\OSGeo4W\Lizmap\Prod\WebClient\lizmap\modules\lizmap\lib\Server\Server.php	54

2023-02-15 06:16:50	::1	error	The lizmap_server plugin needs to be updated.
```

### Steps to reproduce the issue

Lizmap webclient demo, Load the map

> Error: "This map cannot be displayed. Please contact the server administrator to check the server information panel."

Lizmap webclient: 3.6.1
Lizmap Server: 1.3.1
PHP: 8.2.3

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.16-Białowieża | QGIS code revision | 6f08e4d7
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | 14.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows Server 2008 R2 Version 6.1 (Build 7601: SP 1)
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
go2streetview | 8.6
lizmap | 3.10.1
mmqgis | 2021.9.10
pgRoutingLayer | 3.0.2
pg_metadata | 1.2.1
qgis2web | 3.16.0
QuickOSM | 2.1.1
quick_map_services | 0.19.33
SemiAutomaticClassificationPlugin | 7.10.10

</body></html>QGIS version
3.22.16-Białowieża
QGIS code revision
[6f08e4d7](https://github.com/qgis/QGIS/commit/6f08e4d7)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows Server 2008 R2 Version 6.1 (Build 7601: SP 1)

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
go2streetview
8.6
lizmap
3.10.1
mmqgis
2021.9.10
pgRoutingLayer
3.0.2
pg_metadata
1.2.1
qgis2web
3.16.0
QuickOSM
2.1.1
quick_map_services
0.19.33
SemiAutomaticClassificationPlugin
7.10.10

### Check Lizmap plugin

- [ ] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.22.16.1 ltr

### Operating system

Windows Server 2008 R2

### Browsers

Firefox

### Browsers version

109.0.1 (64bit)

**Comment by Gustry** [comment] 2023-02-15 09:12
>  I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

You must do the step in the Lizmap plugin. https://docs.lizmap.com/current/en/publish/lizmap_plugin/information.html#request-for-support

Please have a look to the error written, did you check it ? Are you sure you are running 1.3.1, the one executed by QGIS server ?

> Error: "This map cannot be displayed. Please contact the server administrator to check the server information panel."

**Comment by WarpNine88** [comment] 2023-02-16 01:17
**Versions :**

* Lizmap Web Client : 3.5.10
* Lizmap Web Client target version : 3.5
* Lizmap plugin : 3.10.1
* QGIS Desktop : 3.22.16
* QGIS Server and plugins unknown status because of the settings in QGIS Server, please review your server settings in the Lizmap Web Client administration interface, then in the "Server Information" panel.

This Lizmap webclient 3.5.10 running well on the same machine, even I cannot get the QGIS server information.
![lizmap-3 5 10](https://user-images.githubusercontent.com/125436120/219234408-64ef55c6-2196-43a4-b50d-8a9e51129cbe.png)

![QGIS-Desktop-3 22 16 1-ltr-Lizmap](https://user-images.githubusercontent.com/125436120/219235535-a85e945a-81d7-4be6-8915-7e6490d56068.png)

**Comment by WarpNine88** [comment] 2023-02-16 01:31
using the same machine I rename the previous Lizmap directory and install the new one, Lizmap webclient 3.6.1

**Versions :**

* Lizmap Web Client : 3.6.1
* Lizmap Web Client target version : 3.5
* Lizmap plugin : 3.10.1
* QGIS Desktop : 3.22.16
* QGIS Server and plugins unknown status because of the settings in QGIS Server, please review your server settings in the Lizmap Web Client administration interface, then in the "Server Information" panel.

![QGIS-Desktop-3 22 16 1-ltr-Lizmap-3
![lizmap-3 6 1](https://user-images.githubusercontent.com/125436120/219239499-e336cc0a-b6ee-4b28-84d9-02dac65a7672.png)
61](https://user-images.githubusercontent.com/125436120/219239401-319e3fa2-c8d3-48a3-8f2d-76928810baec.png)
![Lizmap-web-3 6 1-load-map-error](https://user-images.githubusercontent.com/125436120/219239705-a2dc9f00-48ba-46f0-b591-f2f535f8d05c.png)

**Comment by Gustry** [comment] 2023-02-16 06:38
> This Lizmap webclient 3.5.10 running well on the same machine, even I cannot get the QGIS server information.

> QGIS Server and plugins unknown status because of the settings in QGIS Server, please review your server settings in the Lizmap Web Client administration interface, then in the "Server Information" panel.

Yes, but a link is provided in your screenshot in your **Server information** panel to the documentation about the **Environment variable**.

Duplicate of #3367

**Closed by Gustry** 2023-02-16 06:38 UTC
Labels: bug, feedback
