### ISSUE TITLE
[Question]: Print user information

### ISSUE THREAD

**Issue by jserieye** [3liz/lizmap-web-client#3963] opened 2023-11-14 09:55 UTC
### What is the question?

I use the code below to retrieve information about the logged in user
 
```javascript
var login = $('#info-user-login').text();
console.log(login );
``` 
 
For the login, lastname and firstname variables it works.
By I have no return for email, phone, organization, postcode, city, comment, ...

The goal is to be able to reuse these variables to personalize layouts, for example with the organization's logo.

### Versions

**Versions :**

* Lizmap Web Client : 3.6.6-pre.6247
* Lizmap plugin : 3.18.1
* QGIS Desktop : 3.28.11
* QGIS Server : 3.28.10
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin cadastre : 1.18.0
* QGIS Server plugin lizmap_server : 2.8.0
* QGIS Server plugin wfsOutputExtension : 1.8.0

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### QGIS server version, only if the section above doesn't mention the QGIS Server version

3.28.10

### Operating system

Ubuntu

### Browsers

Chrome

### Browsers version

Chrome

**Comment by Gustry** [comment] 2023-11-14 11:27
Kind of duplicate of a question asked last Friday #3960

**Closed by Gustry** 2023-11-14 11:27 UTC
Labels: question
