### ISSUE TITLE
Parent/child project odd behaviour - LWC 2.11

### ISSUE THREAD

**Issue by pieri70** [3liz/lizmap-web-client#177] opened 2015-07-10 06:32 UTC
Dear 3Liz team
We are starting to use lizmap in our organization
http://lizmap.arpa.fvg.it/
I'm working on an european project (ecosea) that collect lots of data/many layers so I thought to split them in many parent/child qgis project following this guide:

http://docs.3liz.com/en/publisher_guide/advanced_lizmap_config.html#centralizing-the-cache-with-the-integration-of-groups-and-layers-from-a-master-project

This solution is to better manage tiles and cache on our server.
The experiment on parent/child is on my local virtual machine running debian jessie, qgis-server 2.8.2 (and 2.10 in latest tests) and lizmap web client 2.11.

All data are on server and are in shp file format.

The system run pretty smooth but with parent/child projects I encounter some problems.

We created many parent projects, published them in OWS tab with qgis desktop 2.8.2 and set their cache (on server) and image properties with lizmap plugin.
Then we created a child qgis project loading layers and groups from parents and setting the same cache and image properties for all layers coming from parents as they are set in parents.

Like this everything works correctly..
But...

If we add a new layer in a parent project, set its properties in lizmap plugin, and then add it to the child project (with same cache/image properties set in LPlugin) then the child project stop to load all its layers (the loading icon appears and nothing happens).
The parent project with the new added layer stops to work, or better, loads its layers (loading icon disappear) but they are blank, no feature is shown.

I took a look at "top" output in debian, to see what processes are in use, and qgis server fast cgi start to run at 99% CPU, no change in memory usage and it remains like that all the time.

If I delete the new layer added to child does not solve the problem:

Father layers once charged (charging circle icons disappear) are blank
The child shows only the loading Icon running (qgis server at 99% CPU usage)

If you delete all the "broken father" layers from the child project, the child project starts to work properly and shows all layers coming from other father projects.

If you re-create the "broken parent project" from scratch and re-create the relationship and all settings:
The parent project shows some but not all layers and the child project works, but shows only those layers displayed by the parent project.

We tried to erase the cache both from single layers/project and on the entire repository without success..

Is that normal??

Is there any other solution we can try to solve this problem?

Thanks for your help
Best regards
Pietro Rossin

**Comment by mdouchin** [comment] 2015-07-10 07:46
Hi,

You really need to check these kind of things with very simple projects (parents and child)
My first concern is about the parent project, working once, but then not working any more just because you added a layer and reconfigure it.
You should not focus on the child projects (they won't work if parent project does not), but first on the problem with the modified parent project.

You need to check first if the issue is with QGIS Server or Lizmap (which basically just uses QGIS Server)
Have you tried to access you parent project layers from QGIS via WMS connection, using the QGIS Server URL, such as http://localhost/cgi-bin/qgis_mapserv.fcgi?map=/your/path/to/project.qgs$SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0

**Comment by pieri70** [comment] 2015-07-10 07:48
Ok, I'll make some other test, as you suggested, and report back.
Thanks
Pietro

**Comment by pieri70** [comment] 2015-07-23 09:27
So we made some other test
after having some headaches we found that the only way to make parent/child working again was to re upload and overwrite those shp files that were newly added.
There is a kind of lock on these files..
Any solution??
Thanks
Pietro

**Comment by rldhont** [comment] 2015-09-02 18:15
Hi @pieri70, did you test QGIS-Server without lizmap ? The issue you describe is probably a QGIS-Server one.

**Comment by rldhont** [comment] 2016-04-22 15:59
I allows me to close this issue, feel free to reopen if needed

**Closed by rldhont** 2016-04-22 15:59 UTC
Labels: question
