### ISSUE TITLE
[Question]: is it normal to loose (almost all) the layer configuration in the lizmap plugin when renaming the layer in qgis?

### ISSUE THREAD

**Issue by sigsdis30** [3liz/lizmap-web-client#4555] opened 2024-06-25 15:24 UTC
### What is the question? (in English)

When renaming in qgis I loose almost all my layer conf in the plugin except the title. 
To reproduce:
1. add a layer to your project
2. config the layer in the lizmap plugin (add an alias, some filter on users, popup etc.)
3. in qgis rename the layer
4. go back to lizmap plugin on this layer, your previous config is gone, only the title remains.

In the cfg I saw that your key is the name of the layer, but why do I loose everything? it’s not like a source change. Renaming seems trivial. It bothers me especially when adding some filter on users, because if I forget to check the filter is gone. So is it normal? If so, why just the title remains? I was not sure if it was a bug or not, so I ask a question.

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.9-pre.7533
* Lizmap plugin : 4.3.16
* QGIS Desktop : 3.28.11
* Lizmap.com : Yes
* QGIS Server : 3.28.15
* Py-QGIS-Server : 1.8.8
* QGIS Server plugin atlasprint : 3.4.1

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Windows 10

### Browsers

Firefox

### Browsers version

Firefox 127.0.1

**Comment by Gustry** [comment] 2024-06-27 07:43
You must have a warning when your layer is renamed, as written below, asking you to check your **Layers** tab.

![Peek 2024-06-27 09-39](https://github.com/3liz/lizmap-web-client/assets/1609292/512560c1-9ca1-4c69-bec7-6936ca7c7378)

Other tabs (like "Filter by user" are not lost)

It's a duplicate of https://github.com/3liz/lizmap-plugin/issues/498, feel free to continue there.

**Closed by Gustry** 2024-06-27 07:43 UTC
Labels: question
