### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by katagen** [3liz/lizmap-web-client#4691] opened 2024-08-11 07:13 UTC
Google Analytics 3 is outdated since a moment.
Now it is Google Analytics 4, which has ID Tracking that starts with G-xxxxxxx.
In Lizmap Web Client, in Admin Configuration Panel, we can only add an old ID Tracking with UA-xxxxxx.

**Comment by Gustry** [comment] 2024-08-12 09:09
Duplicate of #2355

**Closed by Gustry** 2024-08-12 09:09 UTC
Labels: enhancement, Sponsor or PR needed
