### ISSUE TITLE
[Bug]: Checkbox not in all Layer categories 

### ISSUE THREAD

**Issue by AdiTane** [3liz/lizmap-web-client#4272] opened 2024-03-06 09:44 UTC
### What is the bug? (in English)

After updating to Lizmap 3.7.5 I notice that the checkbox is not displayed in all the categories of the layers. It seems that only categories with less than 10 features have the checkbox. This happens in all browsers

### Steps to reproduce the issue

1. Upgrade from 3.6.8 to 3.7.5
2. Screenshots for 3.7.5

Lizmap web result
![web 3-7-5](https://github.com/3liz/lizmap-web-client/assets/162430427/537330d1-b118-411b-9f09-d4e9bfbd0785)

Lizmap configuration
![Lizmap 3-7-5](https://github.com/3liz/lizmap-web-client/assets/162430427/50354b68-4bb0-46df-ab58-8e95ee1e5592)

Qgis layers
![qgis 3-7-5](https://github.com/3liz/lizmap-web-client/assets/162430427/573c83f3-e320-4500-9a7c-501297f01af1)

3. Screenshots for 3.6.8
Lizmap web result
![web 3-6-8](https://github.com/3liz/lizmap-web-client/assets/162430427/fec4023f-ecbf-4a63-b034-8815aca12ef0)

Lizmap configuration
![Lizmap 3-6-8](https://github.com/3liz/lizmap-web-client/assets/162430427/b8a1b0fe-b7f3-4e29-874d-3c09db0684d8)

Qgis layers
![qgis 3-6-8](https://github.com/3liz/lizmap-web-client/assets/162430427/ce9f9e3c-c804-40dc-914f-1f47e84b827e)

### Versions, safeguards, check summary etc

**Versions :**

* Lizmap Web Client : 3.7.5
* Lizmap plugin : 4.2.4
* QGIS Desktop : 3.22.16
* QGIS Server : 3.22.16
* Py-QGIS-Server : not used
* QGIS Server plugin atlasprint : 3.3.2
* QGIS Server plugin lizmap_server : 2.8.4
* QGIS Server plugin wfsOutputExtension : 1.8.0

<details>
<summary>List of safeguards :</summary>
<br/>

* Mode : safe
* Allow parent folder : no
* Prevent other drive : yes
* Prevent PG service : yes
* Prevent PG Auth DB : yes
* Force PG user&pass : yes
* Prevent ECW : yes
</details>

### Check Lizmap plugin

- [X] I have done the step just before in the Lizmap QGIS desktop plugin before opening this ticket. Otherwise, my ticket is not considered valid and might get closed.

### Operating system

Ubuntu 20.04.6 LTS

### Browsers

Chrome

### Browsers version

Chrome Version 121.0.6167.185

**Comment by Gustry** [comment] 2024-03-06 09:49
Duplicate of #4026 ?

**Comment by AdiTane** [comment] 2024-03-06 10:07
> Duplicate of #4026 ?

You are correct but I wanted to point out since this happened also with the latest release of 3.7

**Comment by Gustry** [comment] 2024-03-06 10:15
I think you should provide your feedback and context there, so it can be centralized. Thanks

**Closed by Gustry** 2024-03-06 10:15 UTC
Labels: bug, feedback
