### ISSUE TITLE
Layers from Postgres SQL can't be load in Lizmap 3.3.6

### ISSUE THREAD

**Issue by tomgardes** [3liz/lizmap-web-client#1659] opened 2020-05-28 10:08 UTC
Hi,

I'm trying to configure Lizmap  3.3.6 on Ubuntu 20.04, using QGIS Server, QGIS Desktop 3.10.6 (LTR), Apache and Postgres SQL 12.3.

When I load a shapefile in my QGIS desktop project and try to show it in Lizmap, everything work fine.
But if I try to use the same layer from a PostGres database, it load endlessly, showing "Service Non Disponible".

I get no error logs from Apache and from PostGres. 
**From Lizmap logs, I get :**

2020-05-28 11:32:11	127.0.0.1	warning	2020-05-28 11:32:11	[2]	file_get_contents(http://localhost/cgi-bin/qgis_mapserv.fcgi?map=%2Fusr%2Flib%2Fcgi%2Dbin%2Fproject%2Fqgis%5Ftest%2Eqgs&amp;request=GetCapabilities&amp;service=WFS&amp;version=1%2E0%2E0): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error
	/var/www/lizmap-web-client-3.3.6/lizmap/modules/lizmap/classes/lizmapProxy.class.php	240

2020-05-28 11:32:11	127.0.0.1	error	GetCapabilities empty data

**From QGIS server logs, I get :** 

11:32:11 CRITICAL Server[212268]: Error, Layer(s) jacksonetal_gis_1ad06b92_86bd_40d6_8a3f_9bae1ee504fd not valid in project /usr/lib/cgi-bin/project/qgis_test.qgs
11:32:11 WARNING Server[212268]: <ServerException>Layer(s) not valid</ServerException>

11:32:11 INFO Server[212268]: Request finished in 11 ms

**If I test the getCapabilites request by typing** http://localhost/cgi-bin/project/qgis_mapserv.fcgi?map=%2Fusr%2Flib%2Fcgi-bin%2Fproject%2Fqgis_test.qgs&request=GetCapabilities&service=WFS&version=1.0.0 **in my browser, I get ;**

< ServerException> Layer(s) not valid < /ServerException >

The QGIS demo projects (Montpellier_transports ...) works fine in Lizmap, as well as my personnal projects from local shapefile datasource. Only layers from PostGresSQL are not working.

I have opened a PostGresSQL connection in my QGIS desktop project and it seems to work fine : I can add the layers from database to my project, configure it in Lizmap plugin, and all needed tables seems to have been created.

![image](https://user-images.githubusercontent.com/27816655/83127042-f52dfa80-a0d9-11ea-998e-0b14146297b6.png)

My Qgis project properties seems fine, with saving path set to relative and Qgis server properties set like this : 

![image](https://user-images.githubusercontent.com/27816655/83127283-4342fe00-a0da-11ea-9553-29ab9874311f.png)

I also configured the profiles.ini.php : 

![image](https://user-images.githubusercontent.com/27816655/83127491-83a27c00-a0da-11ea-8486-f60733b1f453.png)

I finally have tried to load the working demo project ("Montpellier_transport") and add to it a PosgresSQL layer, and I get the same errors.

![image](https://user-images.githubusercontent.com/27816655/83127749-d3814300-a0da-11ea-9f66-293fc9f4c1c7.png)

My Lizmap general configuration seems fine to me : 

![image](https://user-images.githubusercontent.com/27816655/83127907-01ff1e00-a0db-11ea-810f-d19c2e3aa09b.png)

I need to use layers from PostgresSQL beacause I need to make features editable in Lizmap.
I guess I'm doing something wrong but I really can't find what...

Thank you for you help !

**Comment by Gustry** [comment] 2020-05-28 10:31
Duplicate of #1638 
Check at the bottom.

If it doesn't work, please reopen the ticket.

**Closed by Gustry** 2020-05-28 10:31 UTC
Labels: question

**Comment by tomgardes** [comment] 2020-05-28 13:50
Thank you for you answer ! 
It's finally working !

I have checked the ticket you suggested, and done some adjustement according to it (but most of my configurations was already fine).
But it finally turns out that the problem came from my qgis project repository, which, for some reason, was set with roots permissions. I have change it to give user permission (using chown command ) and it works now !

Thank you,

**Comment by franyam2006** [comment] 2020-10-01 01:59
Bonjour tomgardes, jai exactement le meme soucis que vous aviez eu. Pouvez vous me revenir plus en détails sur comment vous avez procédé ? Jai des couche postgresql que jai chargé sur qgis. et jai pu configuré le projet ainsi que le plugin lizmap, défini aussi le referentiel et tout mais lorsque je charge sur lizmap web jai ' service indisponible'. Je ne comprends pas bien les parametrage dans le profiles.ini.php. merci

**Comment by Gustry** [comment] 2020-10-01 09:23
@franyam2006 Comme mentioné dans #1836, pour utiliser des couches PostgresSQL dans Lizmap, il n'y a pas besoin de modifier le `profiles.ini`. Ce sont 2 choses distinctes.
Pour juste **afficher** des couches PG dans Lizmap, vous devez vous assurer que le serveur Lizmap puisse joindre le postgresql (login et MDP dans le fichier QGS par ex)
