### ISSUE TITLE
filter tool for multiple layers - only one layer at a time

### ISSUE THREAD

**Issue by josemvm** [3liz/lizmap-web-client#2350] opened 2021-06-19 11:07 UTC
hi 

when we switch from one layer to another layer, the lizmap losts all the selections from previous layer
so we can not use multiple filters at the same time!...

thanks for your attention

LMWC 3.4.4-pre and QGIS Server 3.16 on Ubuntu Server 20.04

**Comment by gioman** [comment] 2021-06-19 15:38
Duplicate of https://github.com/3liz/lizmap-web-client/issues/2301 ?

**Comment by josemvm** [comment] 2021-06-20 18:45
yes, i think so

**Closed** 2021-09-13 15:59 UTC
Labels: bug
